apiVersion: content.hauler.cattle.io/v1
kind: Files
metadata:
  name: rancher-airgap-files-hauler
spec:
  files:
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.2.1/hauler_1.2.1_linux_amd64.tar.gz
      name: hauler-linux-amd64.tar.gz
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.2.1/hauler_1.2.1_linux_arm64.tar.gz
      name: hauler-linux-arm64.tar.gz
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.2.1/hauler_1.2.1_darwin_amd64.tar.gz
      name: hauler-darwin-amd64.tar.gz
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.2.1/hauler_1.2.1_darwin_arm64.tar.gz
      name: hauler-darwin-arm64.tar.gz
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.2.1/hauler_1.2.1_windows_amd64.tar.gz
      name: hauler-windows-amd64.tar.gz
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.2.1/hauler_1.2.1_windows_arm64.tar.gz
      name: hauler-windows-arm64.tar.gz
---
apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: rancher-airgap-charts-hauler
spec:
  charts:
    - name: hauler-helm
      repoURL: oci://ghcr.io/hauler-dev
      version: 2.0.1
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-hauler
spec:
  images:
    - name: ghcr.io/hauler-dev/hauler:1.2.1
    - name: ghcr.io/hauler-dev/hauler-debug:1.2.1
