apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: rancher-airgap-files-hauler
spec:
  files:
    - path: https://github.com/rancherfederal/hauler/releases/download/v1.0.2/hauler_1.0.2_linux_amd64.tar.gz
      name: hauler-linux-amd64.tar.gz
    - path: https://github.com/rancherfederal/hauler/releases/download/v1.0.2/hauler_1.0.2_linux_arm64.tar.gz
      name: hauler-linux-arm64.tar.gz
