apiVersion: content.hauler.cattle.io/v1
kind: Files
metadata:
  name: rancher-airgap-files-hauler
spec:
  files:
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.3.0/hauler_1.3.0_linux_amd64.tar.gz
      name: hauler-linux-amd64.tar.gz
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.3.0/hauler_1.3.0_linux_arm64.tar.gz
      name: hauler-linux-arm64.tar.gz
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.3.0/hauler_1.3.0_darwin_amd64.tar.gz
      name: hauler-darwin-amd64.tar.gz
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.3.0/hauler_1.3.0_darwin_arm64.tar.gz
      name: hauler-darwin-arm64.tar.gz
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.3.0/hauler_1.3.0_windows_amd64.tar.gz
      name: hauler-windows-amd64.tar.gz
    - path: https://github.com/hauler-dev/hauler/releases/download/v1.3.0/hauler_1.3.0_windows_arm64.tar.gz
      name: hauler-windows-arm64.tar.gz
---
apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: rancher-airgap-charts-hauler
spec:
  charts:
    - name: hauler-helm
      repoURL: oci://ghcr.io/hauler-dev
      version: 2.1.0
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-hauler
spec:
  images:
    - name: ghcr.io/hauler-dev/hauler:1.3.0
    - name: ghcr.io/hauler-dev/hauler-debug:1.3.0
