apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: rancher-airgap-files-longhorn
spec:
  files:
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/longhorn-encrypted-sc.yaml
      name: longhorn-encrypted-sc.yaml
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/longhorn-encrypted-volume.yaml
      name: longhorn-encrypted-volume.yaml
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: rancher-airgap-charts-longhorn
spec:
  charts:
    - name: longhorn
      repoURL: https://charts.longhorn.io
      version: 1.7.1
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-images-longhorn
spec:
  images:
    - name: longhornio/csi-attacher:v4.6.1
    - name: longhornio/csi-provisioner:v4.0.1
    - name: longhornio/csi-resizer:v1.11.1
    - name: longhornio/csi-snapshotter:v7.0.2
    - name: longhornio/csi-node-driver-registrar:v2.12.0
    - name: longhornio/livenessprobe:v2.14.0
    - name: longhornio/openshift-origin-oauth-proxy:4.15
    - name: longhornio/backing-image-manager:v1.7.1
    - name: longhornio/longhorn-engine:v1.7.1
    - name: longhornio/longhorn-instance-manager:v1.7.1
    - name: longhornio/longhorn-manager:v1.7.1
    - name: longhornio/longhorn-share-manager:v1.7.1
    - name: longhornio/longhorn-ui:v1.7.1
    - name: longhornio/longhorn-cli:v1.7.1
    - name: longhornio/support-bundle-kit:v0.0.42
