apiVersion: content.hauler.cattle.io/v1
kind: Files
metadata:
  name: rancher-airgap-files-longhorn
spec:
  files:
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/longhorn-encrypted-sc.yaml
      name: longhorn-encrypted-sc.yaml
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/longhorn-encrypted-volume.yaml
      name: longhorn-encrypted-volume.yaml
---
apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: rancher-airgap-charts-longhorn
spec:
  charts:
    - name: longhorn
      repoURL: https://charts.longhorn.io
      version: 1.9.1
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-longhorn
spec:
  images:
    - name: longhornio/backing-image-manager:v1.9.1
    - name: longhornio/longhorn-engine:v1.9.1
    - name: longhornio/longhorn-instance-manager:v1.9.1
    - name: longhornio/longhorn-manager:v1.9.1
    - name: longhornio/longhorn-share-manager:v1.9.1
    - name: longhornio/longhorn-ui:v1.9.1
    - name: longhornio/longhorn-cli:v1.9.1
    - name: longhornio/csi-attacher:v4.9.0-20250709
    - name: longhornio/csi-provisioner:v5.3.0-20250709
    - name: longhornio/csi-resizer:v1.14.0-20250709
    - name: longhornio/csi-snapshotter:v8.3.0-20250709
    - name: longhornio/csi-node-driver-registrar:v2.14.0-20250709
    - name: longhornio/livenessprobe:v2.16.0-20250709
    - name: longhornio/support-bundle-kit:v0.0.61
