apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: rancher-airgap-charts-harbor
spec:
  charts:
    - name: harbor
      repoURL: https://helm.goharbor.io
      version: 1.14.0
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-images-harbor
spec:
  images:

