apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: rancher-airgap-charts-harbor
spec:
  charts:
    - name: harbor
      repoURL: https://helm.goharbor.io
      version: 1.15.0
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-images-harbor
spec:
  images:
    - name: goharbor/harbor-core:v2.11.0
    - name: goharbor/harbor-jobservice:v2.11.0
    - name: goharbor/harbor-portal:v2.11.0
    - name: goharbor/registry-photon:v2.11.0
    - name: goharbor/harbor-registryctl:v2.11.0
    - name: goharbor/harbor-db:v2.11.0
    - name: goharbor/harbor-db:v2.11.0
    - name: goharbor/redis-photon:v2.11.0
    - name: goharbor/trivy-adapter-photon:v2.11.0
