apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: rancher-airgap-charts-kubewarden
spec:
  charts:
    - name: kubewarden-controller
      repoURL: https://charts.kubewarden.io
      version: 5.3.0
    - name: kubewarden-defaults
      repoURL: https://charts.kubewarden.io
      version: 3.3.0
    - name: kubewarden-crds
      repoURL: https://charts.kubewarden.io
      version: 1.17.0
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-kubewarden
spec:
  images:
    - name: ghcr.io/kubewarden/kubewarden-controller:v1.25.0
    - name: ghcr.io/kubewarden/audit-scanner:v1.25.0
    - name: ghcr.io/kubewarden/kubectl:v1.31.0
    - name: ghcr.io/kubewarden/policy-server:v1.25.0
