apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: rancher-airgap-charts-kubewarden
spec:
  charts:
    - name: kubewarden-controller
      repoURL: https://charts.kubewarden.io
      version: 5.7.0
    - name: kubewarden-defaults
      repoURL: https://charts.kubewarden.io
      version: 3.7.1
    - name: kubewarden-crds
      repoURL: https://charts.kubewarden.io
      version: 1.21.0
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-kubewarden
spec:
  images:
    - name: ghcr.io/kubewarden/kubewarden-controller:v1.29.0
    - name: ghcr.io/kubewarden/audit-scanner:v1.29.0
    - name: ghcr.io/rancher/kuberlr-kubectl:v5.0.0
    - name: ghcr.io/kubewarden/policy-server:v1.29.1
