apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: rancher-airgap-charts-kubewarden
spec:
  charts:
    - name: kubewarden-controller
      repoURL: https://charts.kubewarden.io
      version: 4.1.0
    - name: kubewarden-defaults
      repoURL: https://charts.kubewarden.io
      version: 2.8.0
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-kubewarden
spec:
  images:


