apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-harvester
spec:
  images:
    - name: ghcr.io/k8snetworkplumbingwg/whereabouts:v0.8.0
    - name: ghcr.io/kube-vip/kube-vip-iptables:v0.8.1
    - name: kubeovn/kube-ovn:v1.13.13
    - name: longhornio/backing-image-manager:v1.9.2
    - name: longhornio/csi-attacher:v4.9.0-20250709
    - name: longhornio/csi-node-driver-registrar:v2.14.0-20250709
    - name: longhornio/csi-provisioner:v5.3.0-20250709
    - name: longhornio/csi-resizer:v1.14.0-20250709
    - name: longhornio/csi-snapshotter:v8.3.0-20250709
    - name: longhornio/livenessprobe:v2.16.0-20250709
    - name: longhornio/longhorn-cli:v1.9.2
    - name: longhornio/longhorn-engine:v1.9.2
    - name: longhornio/longhorn-instance-manager:v1.9.2
    - name: longhornio/longhorn-manager:v1.9.2
    - name: longhornio/longhorn-share-manager:v1.9.2
    - name: longhornio/longhorn-ui:v1.9.2
    - name: longhornio/support-bundle-kit:v0.0.69
    - name: rancher/fleet-agent:v0.13.2
    - name: rancher/fleet:v0.13.2
    - name: rancher/hardened-addon-resizer:1.8.23-build20250909
    - name: rancher/hardened-calico:v3.30.3-build20250909
    - name: rancher/hardened-cluster-autoscaler:v1.10.2-build20250909
    - name: rancher/hardened-cni-plugins:v1.8.0-build20250909
    - name: rancher/hardened-coredns:v1.12.3-build20250909
    - name: rancher/hardened-dns-node-cache:1.26.0-build20250909
    - name: rancher/hardened-etcd:v3.5.21-k3s1-build20250910
    - name: rancher/hardened-flannel:v0.27.3-build20250901
    - name: rancher/hardened-k8s-metrics-server:v0.8.0-build20250909
    - name: rancher/hardened-kubernetes:v1.33.5-rke2r1-build20250910
    - name: rancher/hardened-multus-cni:v4.2.2-build20250909
    - name: rancher/harvester-cluster-repo:v1.6.1
    - name: rancher/harvester-eventrouter:v1.6.1
    - name: rancher/harvester-kubeovn-operator:v1.13.13
    - name: rancher/harvester-load-balancer:v1.6.1
    - name: rancher/harvester-load-balancer-webhook:v1.6.1
    - name: rancher/harvester-network-controller:v1.6.1
    - name: rancher/harvester-networkfs-manager:v1.6.1
    - name: rancher/harvester-network-helper:v1.6.1
    - name: rancher/harvester-network-webhook:v1.6.1
    - name: rancher/harvester-node-disk-manager:v1.6.1
    - name: rancher/harvester-node-disk-manager-webhook:v1.6.1
    - name: rancher/harvester-node-manager:v1.6.1
    - name: rancher/harvester-node-manager-webhook:v1.6.1
    - name: rancher/harvester-pcidevices:v1.6.1
    - name: rancher/harvester-seeder:v1.6.1
    - name: rancher/harvester-upgrade:v1.6.1
    - name: rancher/harvester:v1.6.1
    - name: rancher/harvester-vm-import-controller:v1.6.1
    - name: rancher/harvester-webhook:v1.6.1
    - name: rancher/klipper-helm:v0.9.8-build20250709
    - name: rancher/klipper-lb:v0.4.13
    - name: rancher/kubectl:v1.29.2
    - name: rancher/kubectl:v1.32.3
    - name: rancher/kubectl:v1.33.1
    - name: rancher/mirrored-cluster-api-controller:v1.10.2
    - name: rancher/mirrored-fluent-fluent-bit:3.1.8
    - name: rancher/mirrored-grafana-grafana:11.1.0
    - name: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.4.3
    - name: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.6.2
    - name: rancher/mirrored-kiwigrid-k8s-sidecar:1.27.4
    - name: rancher/mirrored-kube-logging-config-reloader:v0.0.6
    - name: rancher/mirrored-kube-logging-fluentd:v1.16-4.10-full
    - name: rancher/mirrored-kube-logging-logging-operator:4.10.0
    - name: rancher/mirrored-kube-state-metrics-kube-state-metrics:v2.12.0
    - name: rancher/mirrored-library-busybox:1.31.1
    - name: rancher/mirrored-library-busybox:1.36.1
    - name: rancher/mirrored-library-busybox:1.37.0
    - name: rancher/mirrored-library-nginx:1.24.0-alpine
    - name: rancher/mirrored-pause:3.6
    - name: rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.12.0
    - name: rancher/mirrored-prometheus-alertmanager:v0.27.0
    - name: rancher/mirrored-prometheus-node-exporter:v1.8.2
    - name: rancher/mirrored-prometheus-operator-admission-webhook:v0.75.1
    - name: rancher/mirrored-prometheus-operator-prometheus-config-reloader:v0.75.1
    - name: rancher/mirrored-prometheus-operator-prometheus-operator:v0.75.1
    - name: rancher/mirrored-prometheus-prometheus:v2.53.1
    - name: rancher/mirrored-sig-storage-snapshot-controller:v8.2.0
    - name: rancher/nginx-ingress-controller:v1.12.6-hardened1
    - name: rancher/rancher:v2.12.2
    - name: rancher/rancher-webhook:v0.8.2
    - name: rancher/rke2-cloud-provider:v1.33.4-rc1.0.20250814212538-148243c49519-build20250908
    - name: rancher/rke2-runtime:v1.33.5-rke2r1
    - name: rancher/shell:v0.3.0
    - name: rancher/shell:v0.5.0
    - name: rancher/support-bundle-kit:v0.0.57
    - name: rancher/system-agent-installer-rancher:v2.12.2
    - name: rancher/system-agent-installer-rke2:v1.33.5-rke2r1
    - name: rancher/system-agent:v0.3.13-suc
    - name: rancher/system-upgrade-controller:v0.16.0
    - name: registry.k8s.io/sig-storage/snapshot-controller:v6.3.3
    - name: registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.3.3
    - name: registry.suse.com/bci/bci-base:15.6
    - name: registry.suse.com/suse/sles/15.7/cdi-apiserver:1.62.0-150700.9.3.1
    - name: registry.suse.com/suse/sles/15.7/cdi-cloner:1.62.0-150700.9.3.1
    - name: registry.suse.com/suse/sles/15.7/cdi-controller:1.62.0-150700.9.3.1
    - name: registry.suse.com/suse/sles/15.7/cdi-importer:1.62.0-150700.9.3.1
    - name: registry.suse.com/suse/sles/15.7/cdi-operator:1.62.0-150700.9.3.1
    - name: registry.suse.com/suse/sles/15.7/cdi-uploadproxy:1.62.0-150700.9.3.1
    - name: registry.suse.com/suse/sles/15.7/cdi-uploadserver:1.62.0-150700.9.3.1
    - name: registry.suse.com/suse/sles/15.7/libguestfs-tools:1.5.2-150700.3.5.2
    - name: registry.suse.com/suse/sles/15.7/virt-api:1.5.2-150700.3.5.2
    - name: registry.suse.com/suse/sles/15.7/virt-controller:1.5.2-150700.3.5.2
    - name: registry.suse.com/suse/sles/15.7/virt-handler:1.5.2-150700.3.5.2
    - name: registry.suse.com/suse/sles/15.7/virt-launcher:1.5.2-150700.3.5.2
    - name: registry.suse.com/suse/sles/15.7/virt-operator:1.5.2-150700.3.5.2
    - name: registry.suse.com/suse/vmdp/vmdp:2.5.4.2
