apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: rancher-airgap-files-harvester
spec:
  files:
    - path: https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-amd64.iso
      name: harvester-v1.3.0-amd64.iso
    - path: https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-vmlinuz-amd64
      name: harvester-v1.3.0-vmlinuz-amd64
    - path: https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-rootfs-amd64.squashfs
      name: harvester-v1.3.0-rootfs-amd64.squashfs
    - path: https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-amd64.sha512
      name: harvester-v1.3.0-amd64.sha512
    - path: https://releases.rancher.com/harvester/v1.3.0/version.yaml
      name: version.yaml
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-images-harvester
spec:
  images:

