apiVersion: content.hauler.cattle.io/v1
kind: Files
metadata:
  name: rancher-airgap-files-k3s
spec:
  files:
    - path: https://raw.githubusercontent.com/k3s-io/k3s/refs/heads/release-1.31/install.sh
      name: install.sh
    - path: https://github.com/k3s-io/k3s/releases/download/v1.31.8%2Bk3s1/k3s
      name: k3s
    - path: https://github.com/k3s-io/k3s/releases/download/v1.31.8%2Bk3s1/k3s-airgap-images-amd64.tar.zst
      name: k3s-airgap-images-amd64.tar.zst
    - path: https://github.com/k3s-io/k3s/releases/download/v1.31.8%2Bk3s1/sha256sum-amd64.txt
      name: sha256sum-amd64.txt
    - path: https://github.com/k3s-io/k3s/releases/download/v1.31.8%2Bk3s1/k3s-airgap-images-arm64.tar.zst
      name: k3s-airgap-images-arm64.tar.zst
    - path: https://github.com/k3s-io/k3s/releases/download/v1.31.8%2Bk3s1/sha256sum-arm64.txt
      name: sha256sum-arm64.txt
    - path: https://github.com/k3s-io/k3s/releases/download/v1.31.8%2Bk3s1/k3s-arm64
      name: k3s-arm64
    - path: https://github.com/k3s-io/k3s-selinux/releases/download/v1.6.latest.1/k3s-selinux-1.6-1.el9.noarch.rpm
      name: k3s-selinux-1.6-1.el9.noarch.rpm
    - path: https://github.com/k3s-io/k3s-selinux/releases/download/v1.6.latest.1/k3s-selinux-1.6-1.el9.noarch.rpm
      name: k3s-selinux-1.6-1.el8.noarch.rpm
    - path: https://github.com/k3s-io/k3s-selinux/releases/download/v1.6.latest.1/k3s-selinux-1.6-1.el9.noarch.rpm
      name: k3s-selinux-1.6-1.el7.noarch.rpm
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-k3s
spec:
  images:
    - name: rancher/klipper-helm:v0.9.5-build20250306
    - name: rancher/klipper-lb:v0.4.13
    - name: rancher/local-path-provisioner:v0.0.31
    - name: rancher/mirrored-coredns-coredns:1.12.1
    - name: rancher/mirrored-library-busybox:1.36.1
    - name: rancher/mirrored-library-traefik:2.11.24
    - name: rancher/mirrored-metrics-server:v0.7.2
    - name: rancher/mirrored-pause:3.6
