apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: rancher-airgap-charts-gitea
spec:
  charts:
    - name: gitea
      repoURL: https://dl.gitea.com/charts
      version: 12.2.0
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-gitea
spec:
  images:
    - name: docker.io/bitnami/pgpool:4.6.2-debian-12-r7
    - name: docker.gitea.com/gitea:1.24.5-rootless
    - name: docker.gitea.com/gitea:1.24.5-rootless
    - name: docker.gitea.com/gitea:1.24.5-rootless
    - name: docker.gitea.com/gitea:1.24.5-rootless
    - name: docker.io/bitnami/postgresql-repmgr:17.6.0-debian-12-r0
    - name: docker.io/bitnami/valkey-cluster:8.1.3-debian-12-r3
    - name: busybox:latest
