apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: rancher-airgap-files-rke2
spec:
  files:
    - path: https://raw.githubusercontent.com/rancher/rke2/release-1.29/install.sh
      name: install.sh
    - path: https://github.com/rancher/rke2/releases/download/v1.29.8%2Brke2r1/rke2-images.linux-amd64.tar.zst
      name: rke2-images.linux-amd64.tar.zst
    - path: https://github.com/rancher/rke2/releases/download/v1.29.8%2Brke2r1/rke2.linux-amd64.tar.gz
      name: rke2.linux-amd64.tar.gz
    - path: https://github.com/rancher/rke2/releases/download/v1.29.8%2Brke2r1/sha256sum-amd64.txt
      name: sha256sum-amd64.txt
    - path: https://github.com/rancher/rke2/releases/download/v1.29.8%2Brke2r1/rke2.linux-amd64
      name: rke2.linux-amd64
    - path: https://github.com/rancher/rke2/releases/download/v1.29.8%2Brke2r1/rke2-images.linux-arm64.tar.zst
      name: rke2-images.linux-arm64.tar.zst
    - path: https://github.com/rancher/rke2/releases/download/v1.29.8%2Brke2r1/rke2.linux-arm64.tar.gz
      name: rke2.linux-arm64.tar.gz
    - path: https://github.com/rancher/rke2/releases/download/v1.29.8%2Brke2r1/sha256sum-arm64.txt
      name: sha256sum-arm64.txt
    - path: https://github.com/rancher/rke2/releases/download/v1.29.8%2Brke2r1/rke2.linux-arm64
      name: rke2.linux-arm64
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.18.stable.1/rke2-selinux-0.18-1.el9.noarch.rpm
      name: rke2-selinux-0.18-1.el9.noarch.rpm
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.18.stable.1/rke2-selinux-0.18-1.el8.noarch.rpm
      name: rke2-selinux-0.18-1.el8.noarch.rpm
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.18.stable.1/rke2-selinux-0.18-1.el7.noarch.rpm
      name: rke2-selinux-0.18-1.el7.noarch.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.29.8%2Brke2r1.stable.0/rke2-common-1.29.8.rke2r1-0.el9.x86_64.rpm
      name: rke2-common-1.29.8.rke2r1-0.el9.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.29.8%2Brke2r1.stable.0/rke2-common-1.29.8.rke2r1-0.el8.x86_64.rpm
      name: rke2-common-1.29.8.rke2r1-0.el8.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.29.8%2Brke2r1.stable.0/rke2-common-1.29.8.rke2r1-0.el7.x86_64.rpm
      name: rke2-common-1.29.8.rke2r1-0.el7.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.29.8%2Brke2r1.stable.0/rke2-server-1.29.8.rke2r1-0.el9.x86_64.rpm
      name: rke2-server-1.29.8.rke2r1-0.el9.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.29.8%2Brke2r1.stable.0/rke2-server-1.29.8.rke2r1-0.el8.x86_64.rpm
      name: rke2-server-1.29.8.rke2r1-0.el8.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.29.8%2Brke2r1.stable.0/rke2-server-1.29.8.rke2r1-0.el7.x86_64.rpm
      name: rke2-server-1.29.8.rke2r1-0.el7.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.29.8%2Brke2r1.stable.0/rke2-agent-1.29.8.rke2r1-0.el9.x86_64.rpm
      name: rke2-agent-1.29.8.rke2r1-0.el9.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.29.8%2Brke2r1.stable.0/rke2-agent-1.29.8.rke2r1-0.el8.x86_64.rpm
      name: rke2-agent-1.29.8.rke2r1-0.el8.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.29.8%2Brke2r1.stable.0/rke2-agent-1.29.8.rke2r1-0.el7.x86_64.rpm
      name: rke2-agent-1.29.8.rke2r1-0.el7.x86_64.rpm
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-images-rke2
spec:
  images:
    - name: rancher/hardened-addon-resizer:1.8.20-build20240410
    - name: rancher/hardened-calico:v3.28.1-build20240806
    - name: rancher/hardened-cluster-autoscaler:v1.8.10-build20240124
    - name: rancher/hardened-cni-plugins:v1.4.1-build20240325
    - name: rancher/hardened-cni-plugins:v1.4.1-build20240430
    - name: rancher/hardened-cni-plugins:v1.5.1-build20240805
    - name: rancher/hardened-coredns:v1.11.1-build20240305
    - name: rancher/hardened-dns-node-cache:1.22.28-build20240125
    - name: rancher/hardened-etcd:v3.5.13-k3s1-build20240531
    - name: rancher/hardened-flannel:v0.25.5-build20240801
    - name: rancher/hardened-ib-sriov-cni:v1.0.3-build20240327
    - name: rancher/hardened-k8s-metrics-server:v0.7.1-build20240401
    - name: rancher/hardened-kubernetes:v1.29.8-rke2r1-build20240815
    - name: rancher/hardened-multus-cni:v4.0.2-build20240612
    - name: rancher/hardened-node-feature-discovery:v0.15.4-build20240513
    - name: rancher/hardened-sriov-cni:v2.7.0-build20240327
    - name: rancher/hardened-sriov-network-config-daemon:v1.2.0-build20240327
    - name: rancher/hardened-sriov-network-device-plugin:v3.6.2-build20240327
    - name: rancher/hardened-sriov-network-operator:v1.2.0-build20240327
    - name: rancher/hardened-sriov-network-resources-injector:v1.5-build20240327
    - name: rancher/hardened-sriov-network-webhook:v1.2.0-build20240327
    - name: rancher/hardened-whereabouts:v0.7.0-build20240429
    - name: rancher/harvester-cloud-provider:v0.2.1
    - name: rancher/harvester-csi-driver:v0.1.7
    - name: rancher/klipper-helm:v0.8.4-build20240523
    - name: rancher/klipper-lb:v0.4.9
    - name: rancher/mirrored-calico-apiserver:v3.28.1
    - name: rancher/mirrored-calico-cni:v3.28.1
    - name: rancher/mirrored-calico-csi:v3.28.1
    - name: rancher/mirrored-calico-ctl:v3.28.1
    - name: rancher/mirrored-calico-kube-controllers:v3.28.1
    - name: rancher/mirrored-calico-node-driver-registrar:v3.28.1
    - name: rancher/mirrored-calico-node:v3.28.1
    - name: rancher/mirrored-calico-operator:v1.34.3
    - name: rancher/mirrored-calico-pod2daemon-flexvol:v3.28.1
    - name: rancher/mirrored-calico-typha:v3.28.1
    - name: rancher/mirrored-cilium-certgen:v0.2.0
    - name: rancher/mirrored-cilium-cilium-envoy:v1.29.7-39a2a56bbd5b3a591f69dbca51d3e30ef97e0e51
    - name: rancher/mirrored-cilium-cilium:v1.16.0
    - name: rancher/mirrored-cilium-clustermesh-apiserver:v1.16.0
    - name: rancher/mirrored-cilium-hubble-relay:v1.16.0
    - name: rancher/mirrored-cilium-hubble-ui-backend:v0.13.1
    - name: rancher/mirrored-cilium-hubble-ui:v0.13.1
    - name: rancher/mirrored-cilium-operator-aws:v1.16.0
    - name: rancher/mirrored-cilium-operator-azure:v1.16.0
    - name: rancher/mirrored-cilium-operator-generic:v1.16.0
    - name: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.29.0
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.3.0
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.3.0
    - name: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.4.1
    - name: rancher/mirrored-kube-vip-kube-vip-iptables:v0.6.0
    - name: rancher/mirrored-library-busybox:1.36.1
    - name: rancher/mirrored-longhornio-csi-attacher:v3.2.1
    - name: rancher/mirrored-longhornio-csi-node-driver-registrar:v2.3.0
    - name: rancher/mirrored-longhornio-csi-provisioner:v2.1.2
    - name: rancher/mirrored-longhornio-csi-resizer:v1.2.0
    - name: rancher/mirrored-pause:3.6
    - name: rancher/mirrored-sig-storage-csi-attacher:v4.5.1
    - name: rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.10.1
    - name: rancher/mirrored-sig-storage-csi-provisioner:v4.0.1
    - name: rancher/mirrored-sig-storage-csi-resizer:v1.10.1
    - name: rancher/mirrored-sig-storage-csi-snapshotter:v7.0.2
    - name: rancher/mirrored-sig-storage-livenessprobe:v2.12.0
    - name: rancher/mirrored-sig-storage-snapshot-controller:v6.2.1
    - name: rancher/mirrored-sig-storage-snapshot-validation-webhook:v6.2.2
    - name: rancher/nginx-ingress-controller:v1.10.4-hardened2
    - name: rancher/rke2-cloud-provider:v1.29.3-build20240515
    - name: rancher/rke2-runtime:v1.29.8-rke2r1
