apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: rancher-airgap-files-rke2
spec:
  files:
    - path: https://github.com/rancher/rke2/releases/download/v1.25.12%2Brke2r1/rke2-images.linux-amd64.tar.zst
      name: rke2-images.linux-amd64.tar.zst
    - path: https://github.com/rancher/rke2/releases/download/v1.25.12%2Brke2r1/rke2.linux-amd64.tar.gz
      name: rke2.linux-amd64.tar.gz
    - path: https://github.com/rancher/rke2/releases/download/v1.25.12%2Brke2r1/sha256sum-amd64.txt
      name: sha256sum-amd64.txt
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.25.12%2Brke2r1.stable.0/rke2-common-1.25.12.rke2r1-0.x86_64.rpm
      name: rke2-common-1.25.12.rke2r1-0.x86_64.rpm
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.14.stable.1/rke2-selinux-0.14-1.el9.noarch.rpm
      name: rke2-selinux-0.14-1.el9.noarch.rpm
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.14.stable.1/rke2-selinux-0.14-1.el8.noarch.rpm
      name: rke2-selinux-0.14-1.el8.noarch.rpm
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.14.stable.1/rke2-selinux-0.14-1.el7.noarch.rpm
      name: rke2-selinux-0.14-1.el7.noarch.rpm
    - path: https://raw.githubusercontent.com/rancher/rke2/master/install.sh
      name: install.sh
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-images-rke2
spec:
  images:
    - name: docker.io/rancher/hardened-calico:v3.25.1-build20230607
    - name: docker.io/rancher/hardened-cluster-autoscaler:v1.8.6-build20230406
    - name: docker.io/rancher/hardened-cni-plugins:v1.0.1-build20221011
    - name: docker.io/rancher/hardened-cni-plugins:v1.2.0-build20230523
    - name: docker.io/rancher/hardened-coredns:v1.10.1-build20230406
    - name: docker.io/rancher/hardened-dns-node-cache:1.22.20-build20230406
    - name: docker.io/rancher/hardened-etcd:v3.5.7-k3s1-build20230406
    - name: docker.io/rancher/hardened-flannel:v0.22.0-build20230612
    - name: docker.io/rancher/hardened-ib-sriov-cni:v1.0.2-build20221014
    - name: docker.io/rancher/hardened-k8s-metrics-server:v0.6.3-build20230515
    - name: docker.io/rancher/hardened-kubernetes:v1.25.12-rke2r1-build20230719
    - name: docker.io/rancher/hardened-multus-cni:v4.0.2-build20230707
    - name: docker.io/rancher/hardened-sriov-cni:v2.6.3-build20221014
    - name: docker.io/rancher/hardened-sriov-network-config-daemon:v1.2.0-build20221014
    - name: docker.io/rancher/hardened-sriov-network-device-plugin:v3.5.1-build20221014
    - name: docker.io/rancher/hardened-sriov-network-operator:v1.2.0-build20221014
    - name: docker.io/rancher/hardened-sriov-network-resources-injector:v1.5-build20221014
    - name: docker.io/rancher/hardened-sriov-network-webhook:v1.2.0-build20221014
    - name: docker.io/rancher/hardened-whereabouts:v0.6.1-build20230330
    - name: docker.io/rancher/harvester-cloud-provider:v0.2.0
    - name: docker.io/rancher/harvester-csi-driver:v0.1.5
    - name: docker.io/rancher/klipper-helm:v0.8.0-build20230510
    - name: docker.io/rancher/klipper-lb:v0.4.4
    - name: docker.io/rancher/longhornio-csi-attacher:v3.2.1
    - name: docker.io/rancher/longhornio-csi-node-driver-registrar:v2.3.0
    - name: docker.io/rancher/longhornio-csi-provisioner:v2.1.2
    - name: docker.io/rancher/longhornio-csi-resizer:v1.2.0
    - name: docker.io/rancher/mirrored-calico-apiserver:v3.26.1
    - name: docker.io/rancher/mirrored-calico-cni:v3.26.1
    - name: docker.io/rancher/mirrored-calico-ctl:v3.26.1
    - name: docker.io/rancher/mirrored-calico-kube-controllers:v3.26.1
    - name: docker.io/rancher/mirrored-calico-node:v3.26.1
    - name: docker.io/rancher/mirrored-calico-operator:v1.30.4
    - name: docker.io/rancher/mirrored-calico-pod2daemon-flexvol:v3.26.1
    - name: docker.io/rancher/mirrored-calico-typha:v3.26.1
    - name: docker.io/rancher/mirrored-cilium-certgen:v0.1.8
    - name: docker.io/rancher/mirrored-cilium-cilium-etcd-operator:v2.0.7
    - name: docker.io/rancher/mirrored-cilium-cilium:v1.13.2
    - name: docker.io/rancher/mirrored-cilium-clustermesh-apiserver:v1.13.2
    - name: docker.io/rancher/mirrored-cilium-hubble-relay:v1.13.2
    - name: docker.io/rancher/mirrored-cilium-hubble-ui-backend:v0.11.0
    - name: docker.io/rancher/mirrored-cilium-hubble-ui:v0.11.0
    - name: docker.io/rancher/mirrored-cilium-operator-aws:v1.13.2
    - name: docker.io/rancher/mirrored-cilium-operator-azure:v1.13.2
    - name: docker.io/rancher/mirrored-cilium-operator-generic:v1.13.2
    - name: docker.io/rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.25.2
    - name: docker.io/rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.0.1
    - name: docker.io/rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.0.1
    - name: docker.io/rancher/mirrored-ingress-nginx-kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794
    - name: docker.io/rancher/mirrored-kube-vip-kube-vip-iptables:v0.6.0
    - name: docker.io/rancher/mirrored-sig-storage-csi-attacher:v4.2.0
    - name: docker.io/rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.7.0
    - name: docker.io/rancher/mirrored-sig-storage-csi-provisioner:v3.4.0
    - name: docker.io/rancher/mirrored-sig-storage-csi-resizer:v1.7.0
    - name: docker.io/rancher/mirrored-sig-storage-livenessprobe:v2.9.0
    - name: docker.io/rancher/mirrored-sig-storage-snapshot-controller:v6.2.1
    - name: docker.io/rancher/mirrored-sig-storage-snapshot-validation-webhook:v6.2.1
    - name: docker.io/rancher/nginx-ingress-controller:nginx-1.7.1-hardened1
    - name: docker.io/rancher/pause:3.6
    - name: docker.io/rancher/rke2-cloud-provider:v1.26.3-build20230406
    - name: docker.io/rancher/rke2-runtime:v1.25.12-rke2r1
