apiVersion: content.hauler.cattle.io/v1
kind: Files
metadata:
  name: rancher-airgap-files-rke2
spec:
  files:
    - path: https://raw.githubusercontent.com/rancher/rke2/refs/heads/release-1.37/install.sh
      name: install.sh
    - path: https://github.com/rancher/rke2/releases/download/v1.37.7%2Brke2r1/rke2-images.linux-amd64.tar.zst
      name: rke2-images.linux-amd64.tar.zst
    - path: https://github.com/rancher/rke2/releases/download/v1.37.7%2Brke2r1/rke2.linux-amd64.tar.gz
      name: rke2.linux-amd64.tar.gz
    - path: https://github.com/rancher/rke2/releases/download/v1.37.7%2Brke2r1/sha256sum-amd64.txt
      name: sha256sum-amd64.txt
    - path: https://github.com/rancher/rke2/releases/download/v1.37.7%2Brke2r1/rke2.linux-amd64
      name: rke2.linux-amd64
    - path: https://github.com/rancher/rke2/releases/download/v1.37.7%2Brke2r1/rke2-images.linux-arm64.tar.zst
      name: rke2-images.linux-arm64.tar.zst
    - path: https://github.com/rancher/rke2/releases/download/v1.37.7%2Brke2r1/rke2.linux-arm64.tar.gz
      name: rke2.linux-arm64.tar.gz
    - path: https://github.com/rancher/rke2/releases/download/v1.37.7%2Brke2r1/sha256sum-arm64.txt
      name: sha256sum-arm64.txt
    - path: https://github.com/rancher/rke2/releases/download/v1.37.7%2Brke2r1/rke2.linux-arm64
      name: rke2.linux-arm64
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.18.stable.1/rke2-selinux-0.18-1.el9.noarch.rpm
      name: rke2-selinux-0.18-1.el9.noarch.rpm
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.18.stable.1/rke2-selinux-0.18-1.el8.noarch.rpm
      name: rke2-selinux-0.18-1.el8.noarch.rpm
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.18.stable.1/rke2-selinux-0.18-1.el7.noarch.rpm
      name: rke2-selinux-0.18-1.el7.noarch.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.37.7%2Brke2r1.stable.0/rke2-common-1.37.7.rke2r1-0.el9.x86_64.rpm
      name: rke2-common-1.37.7.rke2r1-0.el9.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.37.7%2Brke2r1.stable.0/rke2-common-1.37.7.rke2r1-0.el8.x86_64.rpm
      name: rke2-common-1.37.7.rke2r1-0.el8.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.37.7%2Brke2r1.stable.0/rke2-common-1.37.7.rke2r1-0.el7.x86_64.rpm
      name: rke2-common-1.37.7.rke2r1-0.el7.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.37.7%2Brke2r1.stable.0/rke2-server-1.37.7.rke2r1-0.el9.x86_64.rpm
      name: rke2-server-1.37.7.rke2r1-0.el9.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.37.7%2Brke2r1.stable.0/rke2-server-1.37.7.rke2r1-0.el8.x86_64.rpm
      name: rke2-server-1.37.7.rke2r1-0.el8.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.37.7%2Brke2r1.stable.0/rke2-server-1.37.7.rke2r1-0.el7.x86_64.rpm
      name: rke2-server-1.37.7.rke2r1-0.el7.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.37.7%2Brke2r1.stable.0/rke2-agent-1.37.7.rke2r1-0.el9.x86_64.rpm
      name: rke2-agent-1.37.7.rke2r1-0.el9.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.37.7%2Brke2r1.stable.0/rke2-agent-1.37.7.rke2r1-0.el8.x86_64.rpm
      name: rke2-agent-1.37.7.rke2r1-0.el8.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.37.7%2Brke2r1.stable.0/rke2-agent-1.37.7.rke2r1-0.el7.x86_64.rpm
      name: rke2-agent-1.37.7.rke2r1-0.el7.x86_64.rpm
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-rke2
spec:
  images:

