apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: rancher-airgap-files-rke2
spec:
  files:
    - path: https://github.com/rancher/rke2/releases/download/v1.26.13%2Brke2r1/rke2-images.linux-amd64.tar.zst
      name: rke2-images.linux-amd64.tar.zst
    - path: https://github.com/rancher/rke2/releases/download/v1.26.13%2Brke2r1/rke2.linux-amd64.tar.gz
      name: rke2.linux-amd64.tar.gz
    - path: https://github.com/rancher/rke2/releases/download/v1.26.13%2Brke2r1/sha256sum-amd64.txt
      name: sha256sum-amd64.txt
    - path: https://github.com/rancher/rke2/releases/download/v1.26.13%2Brke2r1/rke2.linux-amd64
      name: rke2.linux-amd64
    - path: https://raw.githubusercontent.com/rancher/rke2/master/install.sh
      name: install.sh
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.17.stable.1/rke2-selinux-0.17-1.el9.noarch.rpm
      name: rke2-selinux-0.17-1.el9.noarch.rpm
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.17.stable.1/rke2-selinux-0.17-1.el8.noarch.rpm
      name: rke2-selinux-0.17-1.el8.noarch.rpm
    - path: https://github.com/rancher/rke2-selinux/releases/download/v0.17.stable.1/rke2-selinux-0.17-1.el7.noarch.rpm
      name: rke2-selinux-0.17-1.el7.noarch.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.26.13%2Brke2r1.stable.0/rke2-common-1.26.13.rke2r1-0.el9.x86_64.rpm
      name: rke2-common-1.26.13.rke2r1-0.el9.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.26.13%2Brke2r1.stable.0/rke2-common-1.26.13.rke2r1-0.el8.x86_64.rpm
      name: rke2-common-1.26.13.rke2r1-0.el8.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.26.13%2Brke2r1.stable.0/rke2-common-1.26.13.rke2r1-0.el7.x86_64.rpm
      name: rke2-common-1.26.13.rke2r1-0.el7.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.26.13%2Brke2r1.stable.0/rke2-server-1.26.13.rke2r1-0.el9.x86_64.rpm
      name: rke2-server-1.26.13.rke2r1-0.el9.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.26.13%2Brke2r1.stable.0/rke2-server-1.26.13.rke2r1-0.el8.x86_64.rpm
      name: rke2-server-1.26.13.rke2r1-0.el8.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.26.13%2Brke2r1.stable.0/rke2-server-1.26.13.rke2r1-0.el7.x86_64.rpm
      name: rke2-server-1.26.13.rke2r1-0.el7.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.26.13%2Brke2r1.stable.0/rke2-agent-1.26.13.rke2r1-0.el9.x86_64.rpm
      name: rke2-agent-1.26.13.rke2r1-0.el9.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.26.13%2Brke2r1.stable.0/rke2-agent-1.26.13.rke2r1-0.el8.x86_64.rpm
      name: rke2-agent-1.26.13.rke2r1-0.el8.x86_64.rpm
    - path: https://github.com/rancher/rke2-packaging/releases/download/v1.26.13%2Brke2r1.stable.0/rke2-agent-1.26.13.rke2r1-0.el7.x86_64.rpm
      name: rke2-agent-1.26.13.rke2r1-0.el7.x86_64.rpm
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-images-rke2
spec:
  images:
    - name: rancher/hardened-calico:v3.26.3-build20231109
    - name: rancher/hardened-cluster-autoscaler:v1.8.6-build20231009
    - name: rancher/hardened-cni-plugins:v1.2.0-build20231009
    - name: rancher/hardened-coredns:v1.10.1-build20231009
    - name: rancher/hardened-dns-node-cache:1.22.20-build20231010
    - name: rancher/hardened-etcd:v3.5.9-k3s1-build20230802
    - name: rancher/hardened-flannel:v0.23.0-build20231109
    - name: rancher/hardened-ib-sriov-cni:v1.0.2-build20231009
    - name: rancher/hardened-k8s-metrics-server:v0.6.3-build20231009
    - name: rancher/hardened-kubernetes:v1.26.13-rke2r1-build20240117
    - name: rancher/hardened-multus-cni:v4.0.2-build20231009
    - name: rancher/hardened-sriov-cni:v2.6.3-build20231009
    - name: rancher/hardened-sriov-network-config-daemon:v1.2.0-build20231010
    - name: rancher/hardened-sriov-network-device-plugin:v3.5.1-build20231009
    - name: rancher/hardened-sriov-network-operator:v1.2.0-build20231010
    - name: rancher/hardened-sriov-network-resources-injector:v1.5-build20231009
    - name: rancher/hardened-sriov-network-webhook:v1.2.0-build20231010
    - name: rancher/hardened-whereabouts:v0.6.3-build20240109
    - name: rancher/harvester-cloud-provider:v0.2.0
    - name: rancher/harvester-csi-driver:v0.1.5
    - name: rancher/klipper-helm:v0.8.2-build20230815
    - name: rancher/klipper-lb:v0.4.5
    - name: rancher/mirrored-calico-apiserver:v3.26.3
    - name: rancher/mirrored-calico-cni:v3.26.3
    - name: rancher/mirrored-calico-ctl:v3.26.3
    - name: rancher/mirrored-calico-kube-controllers:v3.26.3
    - name: rancher/mirrored-calico-node:v3.26.3
    - name: rancher/mirrored-calico-operator:v1.30.7
    - name: rancher/mirrored-calico-pod2daemon-flexvol:v3.26.3
    - name: rancher/mirrored-calico-typha:v3.26.3
    - name: rancher/mirrored-cilium-certgen:v0.1.9
    - name: rancher/mirrored-cilium-cilium-envoy:v1.26.6-ff0d5d3f77d610040e93c7c7a430d61a0c0b90c1
    - name: rancher/mirrored-cilium-cilium:v1.14.4
    - name: rancher/mirrored-cilium-clustermesh-apiserver:v1.14.4
    - name: rancher/mirrored-cilium-hubble-relay:v1.14.4
    - name: rancher/mirrored-cilium-hubble-ui-backend:v0.12.1
    - name: rancher/mirrored-cilium-hubble-ui:v0.12.1
    - name: rancher/mirrored-cilium-kvstoremesh:v1.14.4
    - name: rancher/mirrored-cilium-operator-aws:v1.14.4
    - name: rancher/mirrored-cilium-operator-azure:v1.14.4
    - name: rancher/mirrored-cilium-operator-generic:v1.14.4
    - name: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.26.1
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.0.1
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.0.1
    - name: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794
    - name: rancher/mirrored-kube-vip-kube-vip-iptables:v0.6.0
    - name: rancher/mirrored-library-busybox:1.36.1
    - name: rancher/mirrored-longhornio-csi-attacher:v3.2.1
    - name: rancher/mirrored-longhornio-csi-node-driver-registrar:v2.3.0
    - name: rancher/mirrored-longhornio-csi-provisioner:v2.1.2
    - name: rancher/mirrored-longhornio-csi-resizer:v1.2.0
    - name: rancher/mirrored-sig-storage-csi-attacher:v4.2.0
    - name: rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.7.0
    - name: rancher/mirrored-sig-storage-csi-provisioner:v3.4.0
    - name: rancher/mirrored-sig-storage-csi-resizer:v1.7.0
    - name: rancher/mirrored-sig-storage-livenessprobe:v2.9.0
    - name: rancher/mirrored-sig-storage-snapshot-controller:v6.2.1
    - name: rancher/mirrored-sig-storage-snapshot-validation-webhook:v6.2.2
    - name: rancher/nginx-ingress-controller:nginx-1.9.3-hardened1
    - name: rancher/pause:3.6
    - name: rancher/rke2-cloud-provider:v1.26.3-build20230406
    - name: rancher/rke2-runtime:v1.26.13-rke2r1
