apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: rancher-airgap-files-rancher-minimal
spec:
  files:
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-ufouo.yaml
      name: rancher-banner-ufouo.yaml
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-tssci.yaml
      name: rancher-banner-tssci.yaml
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: rancher-airgap-charts-rancher-minimal
spec:
  charts:
    - name: cert-manager
      repoURL: https://charts.jetstack.io
      version: v1.13.3
    - name: rancher
      repoURL: https://releases.rancher.com/server-charts/latest
      version: 2.7.9
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-images-rancher-minimal
spec:
  images:
    - name: quay.io/jetstack/cert-manager-cainjector:v1.13.3
    - name: quay.io/jetstack/cert-manager-controller:v1.13.3
    - name: quay.io/jetstack/cert-manager-webhook:v1.13.3
    - name: quay.io/jetstack/cert-manager-ctl:v1.13.3
    - name: rancher/backup-restore-operator:v3.1.2
    - name: rancher/calico-cni:v3.22.5-rancher1
    - name: rancher/calico-cni:v3.24.1-rancher1
    - name: rancher/calico-cni:v3.25.0-rancher1
    - name: rancher/cis-operator:v1.0.12
    - name: rancher/coreos-kube-state-metrics:v1.9.7
    - name: rancher/externalip-webhook:v1.0.1
    - name: rancher/flannel-cni:v0.3.0-rancher6
    - name: rancher/flannel-cni:v0.3.0-rancher7
    - name: rancher/flannel-cni:v0.3.0-rancher8
    - name: rancher/fleet-agent:v0.8.0
    - name: rancher/fleet:v0.8.0
    - name: rancher/gitjob:v0.1.76
    - name: rancher/hardened-calico:v3.22.2-build20220509
    - name: rancher/hardened-calico:v3.24.1-build20221011
    - name: rancher/hardened-calico:v3.24.5-build20221201
    - name: rancher/hardened-calico:v3.25.0-build20230209
    - name: rancher/hardened-calico:v3.25.1-build20230512
    - name: rancher/hardened-calico:v3.25.1-build20230607
    - name: rancher/hardened-calico:v3.26.1-build20230802
    - name: rancher/hardened-cluster-autoscaler:v1.8.5-build20211119
    - name: rancher/hardened-cluster-autoscaler:v1.8.5-build20221011
    - name: rancher/hardened-cluster-autoscaler:v1.8.6-build20230406
    - name: rancher/hardened-cni-plugins:v1.0.1-build20220223
    - name: rancher/hardened-cni-plugins:v1.0.1-build20221011
    - name: rancher/hardened-cni-plugins:v1.2.0-build20230523
    - name: rancher/hardened-coredns:v1.10.1-build20230406
    - name: rancher/hardened-coredns:v1.9.3-build20220613
    - name: rancher/hardened-coredns:v1.9.3-build20221011
    - name: rancher/hardened-dns-node-cache:1.21.2-build20211119
    - name: rancher/hardened-dns-node-cache:1.21.2-build20221011
    - name: rancher/hardened-dns-node-cache:1.22.20-build20230406
    - name: rancher/hardened-etcd:v3.5.4-k3s1-build20220504
    - name: rancher/hardened-etcd:v3.5.4-k3s1-build20221011
    - name: rancher/hardened-etcd:v3.5.7-k3s1-build20230406
    - name: rancher/hardened-etcd:v3.5.9-k3s1-build20230802
    - name: rancher/hardened-flannel:v0.17.0-build20220317
    - name: rancher/hardened-flannel:v0.19.1-build20221011
    - name: rancher/hardened-flannel:v0.20.2-build20221201
    - name: rancher/hardened-flannel:v0.21.1-build20230208
    - name: rancher/hardened-flannel:v0.21.3-build20230308
    - name: rancher/hardened-flannel:v0.22.0-build20230609
    - name: rancher/hardened-flannel:v0.22.0-build20230612
    - name: rancher/hardened-flannel:v0.22.1-build20230802
    - name: rancher/hardened-k8s-metrics-server:v0.5.0-build20211119
    - name: rancher/hardened-k8s-metrics-server:v0.6.1-build20221011
    - name: rancher/hardened-k8s-metrics-server:v0.6.2-build20221202
    - name: rancher/hardened-k8s-metrics-server:v0.6.3-build20230515
    - name: rancher/hardened-kubernetes:v1.23.10-rke2r1-build20220817
    - name: rancher/hardened-kubernetes:v1.23.13-rke2r1-build20221013
    - name: rancher/hardened-kubernetes:v1.23.14-rke2r1-build20221110
    - name: rancher/hardened-kubernetes:v1.23.15-rke2r1-build20221208
    - name: rancher/hardened-kubernetes:v1.23.16-rke2r1-build20230118
    - name: rancher/hardened-kubernetes:v1.23.17-rke2r1-build20230228
    - name: rancher/hardened-kubernetes:v1.24.10-rke2r1-build20230119
    - name: rancher/hardened-kubernetes:v1.24.11-rke2r1-build20230228
    - name: rancher/hardened-kubernetes:v1.24.13-rke2r1-build20230412
    - name: rancher/hardened-kubernetes:v1.24.14-rke2r1-build20230518
    - name: rancher/hardened-kubernetes:v1.24.15-rke2r1-build20230614
    - name: rancher/hardened-kubernetes:v1.24.16-rke2r1-build20230719
    - name: rancher/hardened-kubernetes:v1.24.17-rke2r1-build20230824
    - name: rancher/hardened-kubernetes:v1.24.4-rke2r1-build20220817
    - name: rancher/hardened-kubernetes:v1.24.7-rke2r1-build20221013
    - name: rancher/hardened-kubernetes:v1.24.8-rke2r1-build20221110
    - name: rancher/hardened-kubernetes:v1.24.9-rke2r2-build20230104
    - name: rancher/hardened-kubernetes:v1.25.10-rke2r1-build20230518
    - name: rancher/hardened-kubernetes:v1.25.11-rke2r1-build20230614
    - name: rancher/hardened-kubernetes:v1.25.12-rke2r1-build20230719
    - name: rancher/hardened-kubernetes:v1.25.13-rke2r1-build20230824
    - name: rancher/hardened-kubernetes:v1.25.7-rke2r1-build20230228
    - name: rancher/hardened-kubernetes:v1.25.9-rke2r1-build20230412
    - name: rancher/hardened-kubernetes:v1.26.5-rke2r1-build20230518
    - name: rancher/hardened-kubernetes:v1.26.6-rke2r1-build20230614
    - name: rancher/hardened-kubernetes:v1.26.7-rke2r1-build20230719
    - name: rancher/hardened-kubernetes:v1.26.8-rke2r1-build20230824
    - name: rancher/hardened-node-feature-discovery:v0.13.2-build20230605
    - name: rancher/hardened-whereabouts:v0.5.3-build20220610
    - name: rancher/hardened-whereabouts:v0.5.3-build20221027
    - name: rancher/hardened-whereabouts:v0.6-build20230109
    - name: rancher/hardened-whereabouts:v0.6.1-build20230330
    - name: rancher/hardened-whereabouts:v0.6.2-build20230717
    - name: rancher/helm-project-operator:v0.2.1
    - name: rancher/jimmidyson-configmap-reload:v0.3.0
    - name: rancher/k3s-upgrade:v1.23.10-k3s1
    - name: rancher/k3s-upgrade:v1.23.13-k3s1
    - name: rancher/k3s-upgrade:v1.23.14-k3s1
    - name: rancher/k3s-upgrade:v1.23.15-k3s1
    - name: rancher/k3s-upgrade:v1.23.16-k3s1
    - name: rancher/k3s-upgrade:v1.23.17-k3s1
    - name: rancher/k3s-upgrade:v1.24.10-k3s1
    - name: rancher/k3s-upgrade:v1.24.11-k3s1
    - name: rancher/k3s-upgrade:v1.24.13-k3s1
    - name: rancher/k3s-upgrade:v1.24.14-k3s1
    - name: rancher/k3s-upgrade:v1.24.15-k3s1
    - name: rancher/k3s-upgrade:v1.24.16-k3s1
    - name: rancher/k3s-upgrade:v1.24.17-k3s1
    - name: rancher/k3s-upgrade:v1.24.4-k3s1
    - name: rancher/k3s-upgrade:v1.24.7-k3s1
    - name: rancher/k3s-upgrade:v1.24.8-k3s1
    - name: rancher/k3s-upgrade:v1.24.9-k3s2
    - name: rancher/k3s-upgrade:v1.25.10-k3s1
    - name: rancher/k3s-upgrade:v1.25.11-k3s1
    - name: rancher/k3s-upgrade:v1.25.12-k3s1
    - name: rancher/k3s-upgrade:v1.25.13-k3s1
    - name: rancher/k3s-upgrade:v1.25.7-k3s1
    - name: rancher/k3s-upgrade:v1.25.9-k3s1
    - name: rancher/k3s-upgrade:v1.26.5-k3s1
    - name: rancher/k3s-upgrade:v1.26.6-k3s1
    - name: rancher/k3s-upgrade:v1.26.7-k3s1
    - name: rancher/k3s-upgrade:v1.26.8-k3s1
    - name: rancher/klipper-helm:v0.7.0-build20220315
    - name: rancher/klipper-helm:v0.7.3-build20220613
    - name: rancher/klipper-helm:v0.7.4-build20221121
    - name: rancher/klipper-helm:v0.7.6-build20230223
    - name: rancher/klipper-helm:v0.7.7-build20230403
    - name: rancher/klipper-helm:v0.8.0-build20230510
    - name: rancher/klipper-helm:v0.8.2-build20230815
    - name: rancher/klipper-lb:v0.3.5
    - name: rancher/klipper-lb:v0.4.0
    - name: rancher/klipper-lb:v0.4.3
    - name: rancher/klipper-lb:v0.4.4
    - name: rancher/kube-api-auth:v0.2.0
    - name: rancher/kubectl:v1.20.2
    - name: rancher/kubectl:v1.21.5
    - name: rancher/kubectl:v1.21.9
    - name: rancher/kubectl:v1.22.6
    - name: rancher/kubectl:v1.23.3
    - name: rancher/kubectl:v1.28.1
    - name: rancher/library-nginx:1.19.2-alpine
    - name: rancher/local-path-provisioner:v0.0.21
    - name: rancher/local-path-provisioner:v0.0.23
    - name: rancher/local-path-provisioner:v0.0.24
    - name: rancher/machine:v0.15.0-rancher100
    - name: rancher/nginx-ingress-controller:nginx-1.2.1-hardened7
    - name: rancher/nginx-ingress-controller:nginx-1.2.1-hardened9
    - name: rancher/nginx-ingress-controller:nginx-1.4.1-hardened2
    - name: rancher/nginx-ingress-controller:nginx-1.5.1-rancher2
    - name: rancher/nginx-ingress-controller:nginx-1.7.0-hardened4
    - name: rancher/nginx-ingress-controller:nginx-1.7.0-rancher1
    - name: rancher/nginx-ingress-controller:nginx-1.7.1-hardened1
    - name: rancher/pause:3.6
    - name: rancher/pushprox-client:v0.1.0-rancher2-client
    - name: rancher/pushprox-proxy:v0.1.0-rancher2-proxy
    - name: rancher/rancher-agent:v2.7.9
    - name: rancher/rancher-csp-adapter:v2.0.2
    - name: rancher/rancher-webhook:v0.3.6
    - name: rancher/rancher:v2.7.9
    - name: rancher/rke-tools:v0.1.88
    - name: rancher/rke-tools:v0.1.90
    - name: rancher/rke2-cloud-provider:v0.0.3-build20211118
    - name: rancher/rke2-cloud-provider:v1.25.3-build20221017
    - name: rancher/rke2-cloud-provider:v1.26.1-build20230210
    - name: rancher/rke2-cloud-provider:v1.26.3-build20230406
    - name: rancher/rke2-runtime:v1.23.10-rke2r1
    - name: rancher/rke2-runtime:v1.23.13-rke2r1
    - name: rancher/rke2-runtime:v1.23.14-rke2r1
    - name: rancher/rke2-runtime:v1.23.15-rke2r1
    - name: rancher/rke2-runtime:v1.23.16-rke2r1
    - name: rancher/rke2-runtime:v1.23.17-rke2r1
    - name: rancher/rke2-runtime:v1.24.10-rke2r1
    - name: rancher/rke2-runtime:v1.24.11-rke2r1
    - name: rancher/rke2-runtime:v1.24.13-rke2r1
    - name: rancher/rke2-runtime:v1.24.14-rke2r1
    - name: rancher/rke2-runtime:v1.24.15-rke2r1
    - name: rancher/rke2-runtime:v1.24.16-rke2r1
    - name: rancher/rke2-runtime:v1.24.17-rke2r1
    - name: rancher/rke2-runtime:v1.24.4-rke2r1
    - name: rancher/rke2-runtime:v1.24.7-rke2r1
    - name: rancher/rke2-runtime:v1.24.8-rke2r1
    - name: rancher/rke2-runtime:v1.24.9-rke2r2
    - name: rancher/rke2-runtime:v1.25.10-rke2r1
    - name: rancher/rke2-runtime:v1.25.11-rke2r1
    - name: rancher/rke2-runtime:v1.25.12-rke2r1
    - name: rancher/rke2-runtime:v1.25.13-rke2r1
    - name: rancher/rke2-runtime:v1.25.7-rke2r1
    - name: rancher/rke2-runtime:v1.25.9-rke2r1
    - name: rancher/rke2-runtime:v1.26.5-rke2r1
    - name: rancher/rke2-runtime:v1.26.6-rke2r1
    - name: rancher/rke2-runtime:v1.26.7-rke2r1
    - name: rancher/rke2-runtime:v1.26.8-rke2r1
    - name: rancher/rke2-upgrade:v1.23.10-rke2r1
    - name: rancher/rke2-upgrade:v1.23.13-rke2r1
    - name: rancher/rke2-upgrade:v1.23.14-rke2r1
    - name: rancher/rke2-upgrade:v1.23.15-rke2r1
    - name: rancher/rke2-upgrade:v1.23.16-rke2r1
    - name: rancher/rke2-upgrade:v1.23.17-rke2r1
    - name: rancher/rke2-upgrade:v1.24.10-rke2r1
    - name: rancher/rke2-upgrade:v1.24.11-rke2r1
    - name: rancher/rke2-upgrade:v1.24.13-rke2r1
    - name: rancher/rke2-upgrade:v1.24.14-rke2r1
    - name: rancher/rke2-upgrade:v1.24.15-rke2r1
    - name: rancher/rke2-upgrade:v1.24.16-rke2r1
    - name: rancher/rke2-upgrade:v1.24.17-rke2r1
    - name: rancher/rke2-upgrade:v1.24.4-rke2r1
    - name: rancher/rke2-upgrade:v1.24.7-rke2r1
    - name: rancher/rke2-upgrade:v1.24.8-rke2r1
    - name: rancher/rke2-upgrade:v1.24.9-rke2r2
    - name: rancher/rke2-upgrade:v1.25.10-rke2r1
    - name: rancher/rke2-upgrade:v1.25.11-rke2r1
    - name: rancher/rke2-upgrade:v1.25.12-rke2r1
    - name: rancher/rke2-upgrade:v1.25.13-rke2r1
    - name: rancher/rke2-upgrade:v1.25.7-rke2r1
    - name: rancher/rke2-upgrade:v1.25.9-rke2r1
    - name: rancher/rke2-upgrade:v1.26.5-rke2r1
    - name: rancher/rke2-upgrade:v1.26.6-rke2r1
    - name: rancher/rke2-upgrade:v1.26.7-rke2r1
    - name: rancher/rke2-upgrade:v1.26.8-rke2r1
    - name: rancher/security-scan:v0.2.13
    - name: rancher/shell:v0.1.18
    - name: rancher/shell:v0.1.19
    - name: rancher/shell:v0.1.21
    - name: rancher/system-agent-installer-k3s:v1.21.10-k3s1
    - name: rancher/system-agent-installer-k3s:v1.21.12-k3s1
    - name: rancher/system-agent-installer-k3s:v1.21.13-k3s1
    - name: rancher/system-agent-installer-k3s:v1.21.14-k3s1
    - name: rancher/system-agent-installer-k3s:v1.21.4-k3s1
    - name: rancher/system-agent-installer-k3s:v1.21.5-k3s1
    - name: rancher/system-agent-installer-k3s:v1.21.5-k3s2
    - name: rancher/system-agent-installer-k3s:v1.21.6-k3s1
    - name: rancher/system-agent-installer-k3s:v1.21.7-k3s1
    - name: rancher/system-agent-installer-k3s:v1.21.8-k3s2
    - name: rancher/system-agent-installer-k3s:v1.21.9-k3s1
    - name: rancher/system-agent-installer-k3s:v1.22.10-k3s1
    - name: rancher/system-agent-installer-k3s:v1.22.11-k3s2
    - name: rancher/system-agent-installer-k3s:v1.22.13-k3s1
    - name: rancher/system-agent-installer-k3s:v1.22.15-k3s1
    - name: rancher/system-agent-installer-k3s:v1.22.16-k3s1
    - name: rancher/system-agent-installer-k3s:v1.22.17-k3s1
    - name: rancher/system-agent-installer-k3s:v1.22.4-k3s1
    - name: rancher/system-agent-installer-k3s:v1.22.5-k3s2
    - name: rancher/system-agent-installer-k3s:v1.22.6-k3s1
    - name: rancher/system-agent-installer-k3s:v1.22.7-k3s1
    - name: rancher/system-agent-installer-k3s:v1.22.9-k3s1
    - name: rancher/system-agent-installer-k3s:v1.23.10-k3s1
    - name: rancher/system-agent-installer-k3s:v1.23.13-k3s1
    - name: rancher/system-agent-installer-k3s:v1.23.14-k3s1
    - name: rancher/system-agent-installer-k3s:v1.23.15-k3s1
    - name: rancher/system-agent-installer-k3s:v1.23.16-k3s1
    - name: rancher/system-agent-installer-k3s:v1.23.17-k3s1
    - name: rancher/system-agent-installer-k3s:v1.23.4-k3s1
    - name: rancher/system-agent-installer-k3s:v1.23.6-k3s1
    - name: rancher/system-agent-installer-k3s:v1.23.7-k3s1
    - name: rancher/system-agent-installer-k3s:v1.23.8-k3s2
    - name: rancher/system-agent-installer-k3s:v1.24.10-k3s1
    - name: rancher/system-agent-installer-k3s:v1.24.11-k3s1
    - name: rancher/system-agent-installer-k3s:v1.24.13-k3s1
    - name: rancher/system-agent-installer-k3s:v1.24.14-k3s1
    - name: rancher/system-agent-installer-k3s:v1.24.15-k3s1
    - name: rancher/system-agent-installer-k3s:v1.24.16-k3s1
    - name: rancher/system-agent-installer-k3s:v1.24.17-k3s1
    - name: rancher/system-agent-installer-k3s:v1.24.2-k3s2
    - name: rancher/system-agent-installer-k3s:v1.24.4-k3s1
    - name: rancher/system-agent-installer-k3s:v1.24.7-k3s1
    - name: rancher/system-agent-installer-k3s:v1.24.8-k3s1
    - name: rancher/system-agent-installer-k3s:v1.24.9-k3s2
    - name: rancher/system-agent-installer-k3s:v1.25.10-k3s1
    - name: rancher/system-agent-installer-k3s:v1.25.11-k3s1
    - name: rancher/system-agent-installer-k3s:v1.25.12-k3s1
    - name: rancher/system-agent-installer-k3s:v1.25.13-k3s1
    - name: rancher/system-agent-installer-k3s:v1.25.7-k3s1
    - name: rancher/system-agent-installer-k3s:v1.25.9-k3s1
    - name: rancher/system-agent-installer-k3s:v1.26.5-k3s1
    - name: rancher/system-agent-installer-k3s:v1.26.6-k3s1
    - name: rancher/system-agent-installer-k3s:v1.26.7-k3s1
    - name: rancher/system-agent-installer-k3s:v1.26.8-k3s1
    - name: rancher/system-agent-installer-rke2:v1.21.10-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.21.12-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.21.12-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.21.13-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.21.14-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.21.4-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.21.5-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.21.5-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.21.6-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.21.7-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.21.8-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.21.9-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.22.10-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.22.11-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.22.13-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.22.15-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.22.16-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.22.17-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.22.4-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.22.5-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.22.6-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.22.7-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.22.9-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.22.9-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.23.10-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.23.13-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.23.14-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.23.15-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.23.16-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.23.17-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.23.4-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.23.6-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.23.6-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.23.7-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.23.8-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.10-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.11-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.13-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.14-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.15-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.16-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.17-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.2-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.4-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.7-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.8-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.24.9-rke2r2
    - name: rancher/system-agent-installer-rke2:v1.25.10-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.25.11-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.25.12-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.25.13-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.25.7-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.25.9-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.26.5-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.26.6-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.26.7-rke2r1
    - name: rancher/system-agent-installer-rke2:v1.26.8-rke2r1
    - name: rancher/system-agent:v0.3.3-suc
    - name: rancher/system-upgrade-controller:v0.11.0
    - name: rancher/ui-plugin-operator:v0.1.1
    - name: rancher/webhook-receiver:v0.2.4
    - name: rancher/webhook-receiver:v0.2.5
