apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: rancher-airgap-files-rancher
spec:
  files:
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-ufouo.yaml
      name: rancher-banner-ufouo.yaml
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-tssci.yaml
      name: rancher-banner-tssci.yaml
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: rancher-airgap-charts-rancher
spec:
  charts:
    - name: cert-manager
      repoURL: https://charts.jetstack.io
      version: v1.16.2
    - name: rancher
      repoURL: https://releases.rancher.com/server-charts/latest
      version: 2.9.4
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-cert-manager-images-rancher
spec:
  images:
    - name: quay.io/jetstack/cert-manager-cainjector:v1.16.2
    - name: quay.io/jetstack/cert-manager-controller:v1.16.2
    - name: quay.io/jetstack/cert-manager-webhook:v1.16.2
    - name: quay.io/jetstack/cert-manager-startupapicheck:v1.16.2
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-rancher-images-rancher
spec:
  images:

