apiVersion: content.hauler.cattle.io/v1
kind: Files
metadata:
  name: rancher-airgap-files-rancher-minimal
spec:
  files:
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-ufouo.yaml
      name: rancher-banner-ufouo.yaml
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-tssci.yaml
      name: rancher-banner-tssci.yaml
---
apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: rancher-airgap-charts-rancher-minimal
spec:
  charts:
    - name: cert-manager
      repoURL: https://charts.jetstack.io
      version: v1.16.3
    - name: rancher
      repoURL: https://releases.rancher.com/server-charts/latest
      version: 2.10.1
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-cert-manager-images-rancher-minimal
spec:
  images:

---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-rancher-images-rancher-minimal
spec:
  images:
    - name: rancher/backup-restore-operator:v6.0.0
    - name: rancher/calico-cni:v3.29.0-rancher1
    - name: rancher/cis-operator:v1.3.4
    - name: rancher/flannel-cni:v1.4.1-rancher1
    - name: rancher/fleet-agent:v0.11.2
    - name: rancher/fleet:v0.11.2
    - name: rancher/hardened-addon-resizer:1.8.20-build20241001
    - name: rancher/hardened-calico:v3.29.0-build20241104
    - name: rancher/hardened-cluster-autoscaler:v1.8.11-build20241014
    - name: rancher/hardened-cni-plugins:v1.6.0-build20241022
    - name: rancher/hardened-coredns:v1.11.3-build20241018
    - name: rancher/hardened-dns-node-cache:1.23.1-build20241008
    - name: rancher/hardened-etcd:v3.5.16-k3s1-build20241106
    - name: rancher/hardened-flannel:v0.26.1-build20241107
    - name: rancher/hardened-k8s-metrics-server:v0.7.1-build20241008
    - name: rancher/hardened-kubernetes:v1.31.3-rke2r1-build20241121
    - name: rancher/hardened-whereabouts:v0.8.0-build20241011
    - name: rancher/k3s-upgrade:v1.31.3-k3s1
    - name: rancher/klipper-helm:v0.9.3-build20241008
    - name: rancher/klipper-lb:v0.4.9
    - name: rancher/kube-api-auth:v0.2.3
    - name: rancher/kubectl:v1.31.1
    - name: rancher/local-path-provisioner:v0.0.30
    - name: rancher/machine:v0.15.0-rancher124
    - name: rancher/mirrored-bci-busybox:15.6.24.2
    - name: rancher/mirrored-bci-micro:15.6.24.2
    - name: rancher/mirrored-brancz-kube-rbac-proxy:v0.18.0
    - name: rancher/mirrored-calico-apiserver:v3.29.0
    - name: rancher/mirrored-calico-cni:v3.29.0
    - name: rancher/mirrored-calico-csi:v3.29.0
    - name: rancher/mirrored-calico-ctl:v3.29.0
    - name: rancher/mirrored-calico-kube-controllers:v3.29.0
    - name: rancher/mirrored-calico-node-driver-registrar:v3.29.0
    - name: rancher/mirrored-calico-node:v3.29.0
    - name: rancher/mirrored-calico-operator:v1.36.0
    - name: rancher/mirrored-calico-pod2daemon-flexvol:v3.29.0
    - name: rancher/mirrored-calico-typha:v3.29.0
    - name: rancher/mirrored-cilium-certgen:v0.2.0
    - name: rancher/mirrored-cilium-cilium-envoy:v1.29.9-1728346947-0d05e48bfbb8c4737ec40d5781d970a550ed2bbd
    - name: rancher/mirrored-cilium-cilium:v1.16.3
    - name: rancher/mirrored-cilium-clustermesh-apiserver:v1.16.3
    - name: rancher/mirrored-cilium-hubble-relay:v1.16.3
    - name: rancher/mirrored-cilium-hubble-ui-backend:v0.13.1
    - name: rancher/mirrored-cilium-hubble-ui:v0.13.1
    - name: rancher/mirrored-cilium-operator-aws:v1.16.3
    - name: rancher/mirrored-cilium-operator-azure:v1.16.3
    - name: rancher/mirrored-cilium-operator-generic:v1.16.3
    - name: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.30.1
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.3.1
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.3.1
    - name: rancher/mirrored-cloud-provider-vsphere:v1.31.0
    - name: rancher/mirrored-cluster-api-controller:v1.8.3
    - name: rancher/mirrored-cluster-proportional-autoscaler:v1.8.9
    - name: rancher/mirrored-coredns-coredns:1.11.3
    - name: rancher/mirrored-coreos-etcd:v3.5.15
    - name: rancher/mirrored-curlimages-curl:8.9.1
    - name: rancher/mirrored-elemental-operator:1.6.5
    - name: rancher/mirrored-elemental-seedimage-builder:1.6.5
    - name: rancher/mirrored-flannel-flannel:v0.25.1
    - name: rancher/mirrored-fluent-fluent-bit:3.1.8-debug
    - name: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v20231226-1a7112e06
    - name: rancher/mirrored-jaegertracing-all-in-one:1.63.0
    - name: rancher/mirrored-jimmidyson-configmap-reload:v0.13.1
    - name: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.23.0
    - name: rancher/mirrored-k8s-dns-kube-dns:1.23.0
    - name: rancher/mirrored-k8s-dns-node-cache:1.23.0
    - name: rancher/mirrored-k8s-dns-sidecar:1.23.0
    - name: rancher/mirrored-kiali-kiali:v2.1.0
    - name: rancher/mirrored-kiwigrid-k8s-sidecar:1.27.4
    - name: rancher/mirrored-kube-logging-config-reloader:v0.0.6
    - name: rancher/mirrored-kube-logging-fluentd:v1.16-4.10-full
    - name: rancher/mirrored-kube-logging-logging-operator:4.10.0
    - name: rancher/mirrored-kube-state-metrics-kube-state-metrics:v2.12.0
    - name: rancher/mirrored-kube-vip-kube-vip-iptables:v0.6.0
    - name: rancher/mirrored-library-busybox:1.36.1
    - name: rancher/mirrored-library-nginx:1.24.0-alpine
    - name: rancher/mirrored-library-traefik:2.11.10
    - name: rancher/mirrored-messagebird-sachet:0.3.1
    - name: rancher/mirrored-metrics-server:v0.7.2
    - name: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
    - name: rancher/mirrored-pause:3.7
    - name: rancher/mirrored-sig-storage-csi-attacher:v4.7.0
    - name: rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.12.0
    - name: rancher/mirrored-sig-storage-csi-provisioner:v4.0.1
    - name: rancher/mirrored-sig-storage-csi-resizer:v1.10.1
    - name: rancher/mirrored-sig-storage-csi-snapshotter:v7.0.2
    - name: rancher/mirrored-sig-storage-livenessprobe:v2.14.0
    - name: rancher/mirrored-sig-storage-snapshot-controller:v8.1.0
    - name: rancher/mirrored-sig-storage-snapshot-validation-webhook:v8.1.0
    - name: rancher/mirrored-sonobuoy-sonobuoy:v0.57.2
    - name: rancher/nginx-ingress-controller:v1.10.5-hardened4
    - name: rancher/pushprox-client:v0.1.4-rancher2-client
    - name: rancher/pushprox-proxy:v0.1.4-rancher2-proxy
    - name: rancher/rancher-agent:v2.10.1
    - name: rancher/rancher-csp-adapter:v5.0.1
    - name: rancher/rancher:v2.10.1
    - name: rancher/rancher-webhook:v0.6.2
    - name: rancher/rke2-cloud-provider:v1.31.2-0.20241016053446-0955fa330f90-build20241016
    - name: rancher/rke2-runtime:v1.31.3-rke2r1
    - name: rancher/rke2-upgrade:v1.31.3-rke2r1
    - name: rancher/rke-tools:v0.1.105
    - name: rancher/security-scan:v0.5.2
    - name: rancher/shell:v0.3.0
    - name: rancher/system-agent-installer-k3s:v1.31.3-k3s1
    - name: rancher/system-agent-installer-rke2:v1.31.3-rke2r1
    - name: rancher/system-agent:v0.3.11-suc
    - name: rancher/system-upgrade-controller:v0.14.2
    - name: rancher/ui-plugin-catalog:3.2.0
