apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: rancher-airgap-files-rancher-minimal
spec:
  files:
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-ufouo.yaml
      name: rancher-banner-ufouo.yaml
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-tssci.yaml
      name: rancher-banner-tssci.yaml
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: rancher-airgap-charts-rancher-minimal
spec:
  charts:
    - name: cert-manager
      repoURL: https://charts.jetstack.io
      version: v1.16.2
    - name: rancher
      repoURL: https://releases.rancher.com/server-charts/latest
      version: 2.9.4
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-cert-manager-images-rancher-minimal
spec:
  images:
    - name: quay.io/jetstack/cert-manager-cainjector:v1.16.2
    - name: quay.io/jetstack/cert-manager-controller:v1.16.2
    - name: quay.io/jetstack/cert-manager-webhook:v1.16.2
    - name: quay.io/jetstack/cert-manager-startupapicheck:v1.16.2
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-rancher-images-rancher-minimal
spec:
  images:
    - name: rancher/backup-restore-operator:v5.0.2
    - name: rancher/calico-cni:v3.28.1-rancher1
    - name: rancher/cis-operator:v1.2.0
    - name: rancher/flannel-cni:v1.4.1-rancher1
    - name: rancher/fleet-agent:v0.10.6
    - name: rancher/fleet:v0.10.6
    - name: rancher/hardened-addon-resizer:1.8.20-build20241001
    - name: rancher/hardened-calico:v3.28.2-build20241016
    - name: rancher/hardened-cluster-autoscaler:v1.8.11-build20241014
    - name: rancher/hardened-cni-plugins:v1.5.1-build20241009
    - name: rancher/hardened-coredns:v1.11.3-build20241018
    - name: rancher/hardened-dns-node-cache:1.23.1-build20241008
    - name: rancher/hardened-etcd:v3.5.13-k3s1-build20240910
    - name: rancher/hardened-flannel:v0.25.7-build20241008
    - name: rancher/hardened-k8s-metrics-server:v0.7.1-build20241008
    - name: rancher/hardened-kubernetes:v1.30.6-rke2r1-build20241023
    - name: rancher/hardened-node-feature-discovery:v0.15.6-build20240822
    - name: rancher/hardened-whereabouts:v0.8.0-build20241011
    - name: rancher/k3s-upgrade:v1.30.6-k3s1
    - name: rancher/klipper-helm:v0.9.3-build20241008
    - name: rancher/klipper-lb:v0.4.9
    - name: rancher/kube-api-auth:v0.2.2
    - name: rancher/kubectl:v1.30.5
    - name: rancher/local-path-provisioner:v0.0.30
    - name: rancher/machine:v0.15.0-rancher118
    - name: rancher/mirrored-bci-busybox:15.6.24.2
    - name: rancher/mirrored-bci-micro:15.6.24.2
    - name: rancher/mirrored-calico-apiserver:v3.28.2
    - name: rancher/mirrored-calico-cni:v3.28.2
    - name: rancher/mirrored-calico-csi:v3.28.2
    - name: rancher/mirrored-calico-ctl:v3.28.2
    - name: rancher/mirrored-calico-kube-controllers:v3.28.2
    - name: rancher/mirrored-calico-node-driver-registrar:v3.28.2
    - name: rancher/mirrored-calico-node:v3.28.2
    - name: rancher/mirrored-calico-operator:v1.34.5
    - name: rancher/mirrored-calico-pod2daemon-flexvol:v3.28.2
    - name: rancher/mirrored-calico-typha:v3.28.2
    - name: rancher/mirrored-cilium-certgen:v0.2.0
    - name: rancher/mirrored-cilium-cilium-envoy:v1.29.9-1726784081-a90146d13b4cd7d168d573396ccf2b3db5a3b047
    - name: rancher/mirrored-cilium-cilium-etcd-operator:v2.0.7
    - name: rancher/mirrored-cilium-cilium:v1.16.2
    - name: rancher/mirrored-cilium-clustermesh-apiserver:v1.16.2
    - name: rancher/mirrored-cilium-hubble-relay:v1.16.2
    - name: rancher/mirrored-cilium-hubble-ui-backend:v0.13.1
    - name: rancher/mirrored-cilium-hubble-ui:v0.13.1
    - name: rancher/mirrored-cilium-kvstoremesh:v1.14.4
    - name: rancher/mirrored-cilium-operator-aws:v1.16.2
    - name: rancher/mirrored-cilium-operator-azure:v1.16.2
    - name: rancher/mirrored-cilium-operator-generic:v1.16.2
    - name: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.30.1
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.3.0
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.3.0
    - name: rancher/mirrored-cluster-api-controller:v1.7.3
    - name: rancher/mirrored-cluster-proportional-autoscaler:v1.8.9
    - name: rancher/mirrored-coredns-coredns:1.11.3
    - name: rancher/mirrored-coreos-etcd:v3.5.12
    - name: rancher/mirrored-curlimages-curl:8.10.1
    - name: rancher/mirrored-elemental-operator:1.6.5
    - name: rancher/mirrored-elemental-seedimage-builder:1.6.5
    - name: rancher/mirrored-flannel-flannel:v0.25.1
    - name: rancher/mirrored-fluent-fluent-bit:3.0.4-debug
    - name: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v20231226-1a7112e06
    - name: rancher/mirrored-jaegertracing-all-in-one:1.60.0
    - name: rancher/mirrored-jimmidyson-configmap-reload:v0.8.0
    - name: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.23.0
    - name: rancher/mirrored-k8s-dns-kube-dns:1.23.0
    - name: rancher/mirrored-k8s-dns-node-cache:1.23.0
    - name: rancher/mirrored-k8s-dns-sidecar:1.23.0
    - name: rancher/mirrored-kiali-kiali:v1.89.3
    - name: rancher/mirrored-kiwigrid-k8s-sidecar:1.26.1
    - name: rancher/mirrored-kube-logging-config-reloader:v0.0.5
    - name: rancher/mirrored-kube-logging-fluentd:v1.16-4.8-full
    - name: rancher/mirrored-kube-logging-logging-operator:4.8.0
    - name: rancher/mirrored-kube-rbac-proxy:v0.15.0
    - name: rancher/mirrored-kube-state-metrics-kube-state-metrics:v2.10.1
    - name: rancher/mirrored-kube-vip-kube-vip-iptables:v0.6.0
    - name: rancher/mirrored-library-busybox:1.36.1
    - name: rancher/mirrored-library-nginx:1.24.0-alpine
    - name: rancher/mirrored-library-traefik:2.11.10
    - name: rancher/mirrored-messagebird-sachet:0.3.1
    - name: rancher/mirrored-metrics-server:v0.7.2
    - name: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher1
    - name: rancher/mirrored-openpolicyagent-gatekeeper-crds:v3.13.0
    - name: rancher/mirrored-openpolicyagent-gatekeeper:v3.13.0
    - name: rancher/mirrored-pause:3.7
    - name: rancher/mirrored-sig-storage-csi-attacher:v4.5.1
    - name: rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.10.1
    - name: rancher/mirrored-sig-storage-csi-provisioner:v4.0.1
    - name: rancher/mirrored-sig-storage-csi-resizer:v1.10.1
    - name: rancher/mirrored-sig-storage-csi-snapshotter:v7.0.2
    - name: rancher/mirrored-sig-storage-livenessprobe:v2.12.0
    - name: rancher/mirrored-sig-storage-snapshot-controller:v8.1.0
    - name: rancher/mirrored-sig-storage-snapshot-validation-webhook:v8.1.0
    - name: rancher/mirrored-sonobuoy-sonobuoy:v0.57.2
    - name: rancher/nginx-ingress-controller:v1.10.5-hardened3
    - name: rancher/pushprox-client:v0.1.3-rancher2-client
    - name: rancher/pushprox-proxy:v0.1.3-rancher2-proxy
    - name: rancher/rancher-agent:v2.9.4
    - name: rancher/rancher-csp-adapter:v4.0.0
    - name: rancher/rancher:v2.9.4
    - name: rancher/rancher-webhook:v0.5.4
    - name: rancher/rke2-cloud-provider:v1.30.6-0.20241016053533-5ec454f50e7a-build20241016
    - name: rancher/rke2-runtime:v1.30.6-rke2r1
    - name: rancher/rke2-upgrade:v1.30.6-rke2r1
    - name: rancher/rke-tools:v0.1.105
    - name: rancher/security-scan:v0.4.0
    - name: rancher/shell:v0.2.2
    - name: rancher/system-agent-installer-k3s:v1.30.6-k3s1
    - name: rancher/system-agent-installer-rke2:v1.30.6-rke2r1
    - name: rancher/system-agent:v0.3.10-suc
    - name: rancher/system-upgrade-controller:v0.13.4
    - name: rancher/ui-plugin-catalog:3.0.0
