apiVersion: content.hauler.cattle.io/v1
kind: Files
metadata:
  name: rancher-airgap-files-rancher-minimal
spec:
  files:
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-ufouo.yaml
      name: rancher-banner-ufouo.yaml
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-tssci.yaml
      name: rancher-banner-tssci.yaml
---
apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: rancher-airgap-charts-rancher-minimal
spec:
  charts:
    - name: cert-manager
      repoURL: https://charts.jetstack.io
      version: v1.18.1
    - name: rancher
      repoURL: https://releases.rancher.com/server-charts/latest
      version: 2.11.3
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-cert-manager-images-rancher-minimal
spec:
  images:
    - name: quay.io/jetstack/cert-manager-cainjector:v1.18.1
    - name: quay.io/jetstack/cert-manager-controller:v1.18.1
    - name: quay.io/jetstack/cert-manager-webhook:v1.18.1
    - name: quay.io/jetstack/cert-manager-startupapicheck:v1.18.1
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-rancher-images-rancher-minimal
spec:
  images:
    - name: rancher/backup-restore-operator:v7.0.1
    - name: rancher/calico-cni:v3.29.3-rancher1
    - name: rancher/cis-operator:v1.4.0
    - name: rancher/flannel-cni:v1.4.1-rancher1
    - name: rancher/fleet-agent:v0.12.4
    - name: rancher/fleet:v0.12.4
    - name: rancher/hardened-addon-resizer:1.8.23-build20250507
    - name: rancher/hardened-calico:v3.30.0-build20250515
    - name: rancher/hardened-cluster-autoscaler:v1.10.2-build20250507
    - name: rancher/hardened-cni-plugins:v1.7.1-build20250509
    - name: rancher/hardened-coredns:v1.12.1-build20250507
    - name: rancher/hardened-dns-node-cache:1.26.0-build20250515
    - name: rancher/hardened-etcd:v3.5.21-k3s1-build20250411
    - name: rancher/hardened-flannel:v0.26.7-build20250515
    - name: rancher/hardened-k8s-metrics-server:v0.7.2-build20250507
    - name: rancher/hardened-kubernetes:v1.32.5-rke2r1-build20250515
    - name: rancher/hardened-whereabouts:v0.9.0-build20250403
    - name: rancher/k3s-upgrade:v1.32.5-k3s1
    - name: rancher/klipper-helm:v0.9.5-build20250306
    - name: rancher/klipper-lb:v0.4.13
    - name: rancher/kube-api-auth:v0.2.4
    - name: rancher/kubectl:v1.32.2
    - name: rancher/kuberlr-kubectl:v4.0.2
    - name: rancher/local-path-provisioner:v0.0.31
    - name: rancher/machine:v0.15.0-rancher127
    - name: rancher/mirrored-bci-busybox:15.6.24.2
    - name: rancher/mirrored-bci-micro:15.6.24.2
    - name: rancher/mirrored-brancz-kube-rbac-proxy:v0.18.2
    - name: rancher/mirrored-calico-apiserver:v3.30.0
    - name: rancher/mirrored-calico-cni:v3.30.0
    - name: rancher/mirrored-calico-csi:v3.30.0
    - name: rancher/mirrored-calico-ctl:v3.30.0
    - name: rancher/mirrored-calico-kube-controllers:v3.30.0
    - name: rancher/mirrored-calico-node-driver-registrar:v3.30.0
    - name: rancher/mirrored-calico-node:v3.30.0
    - name: rancher/mirrored-calico-operator:v1.38.0
    - name: rancher/mirrored-calico-pod2daemon-flexvol:v3.30.0
    - name: rancher/mirrored-calico-typha:v3.30.0
    - name: rancher/mirrored-cilium-certgen:v0.2.1
    - name: rancher/mirrored-cilium-cilium-envoy:v1.32.5-1744305768-f9ddca7dcd91f7ca25a505560e655c47d3dec2cf
    - name: rancher/mirrored-cilium-cilium:v1.17.3
    - name: rancher/mirrored-cilium-clustermesh-apiserver:v1.17.3
    - name: rancher/mirrored-cilium-hubble-relay:v1.17.3
    - name: rancher/mirrored-cilium-hubble-ui-backend:v0.13.2
    - name: rancher/mirrored-cilium-hubble-ui:v0.13.2
    - name: rancher/mirrored-cilium-operator-aws:v1.17.3
    - name: rancher/mirrored-cilium-operator-azure:v1.17.3
    - name: rancher/mirrored-cilium-operator-generic:v1.17.3
    - name: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.30.1
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.3.1
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.3.1
    - name: rancher/mirrored-cloud-provider-vsphere:v1.32.2
    - name: rancher/mirrored-cluster-api-controller:v1.9.5
    - name: rancher/mirrored-cluster-proportional-autoscaler:v1.9.0
    - name: rancher/mirrored-coredns-coredns:1.12.1
    - name: rancher/mirrored-coreos-etcd:v3.5.16
    - name: rancher/mirrored-curlimages-curl:8.9.1
    - name: rancher/mirrored-elemental-operator:1.6.9
    - name: rancher/mirrored-elemental-seedimage-builder:1.6.9
    - name: rancher/mirrored-flannel-flannel:v0.26.4
    - name: rancher/mirrored-fluent-fluent-bit:3.1.8-debug
    - name: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.5.2
    - name: rancher/mirrored-jaegertracing-all-in-one:1.67.0
    - name: rancher/mirrored-jimmidyson-configmap-reload:v0.13.1
    - name: rancher/mirrored-k8s-dns-dnsmasq-nanny:1.23.0
    - name: rancher/mirrored-k8s-dns-kube-dns:1.23.0
    - name: rancher/mirrored-k8s-dns-node-cache:1.23.0
    - name: rancher/mirrored-k8s-dns-sidecar:1.23.0
    - name: rancher/mirrored-kiali-kiali:v2.7.1
    - name: rancher/mirrored-kiwigrid-k8s-sidecar:1.30.0
    - name: rancher/mirrored-kube-logging-config-reloader:v0.0.6
    - name: rancher/mirrored-kube-logging-fluentd:v1.16-4.10-full
    - name: rancher/mirrored-kube-logging-logging-operator:4.10.0
    - name: rancher/mirrored-kube-state-metrics-kube-state-metrics:v2.15.0
    - name: rancher/mirrored-kube-vip-kube-vip-iptables:v0.8.7
    - name: rancher/mirrored-library-busybox:1.37.0
    - name: rancher/mirrored-library-nginx:1.27.2-alpine
    - name: rancher/mirrored-library-traefik:3.3.6
    - name: rancher/mirrored-messagebird-sachet:0.3.1
    - name: rancher/mirrored-metrics-server:v0.7.2
    - name: rancher/mirrored-nginx-ingress-controller-defaultbackend:1.5-rancher2
    - name: rancher/mirrored-pause:3.7
    - name: rancher/mirrored-sig-storage-csi-attacher:v4.7.0
    - name: rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.12.0
    - name: rancher/mirrored-sig-storage-csi-provisioner:v4.0.1
    - name: rancher/mirrored-sig-storage-csi-resizer:v1.10.1
    - name: rancher/mirrored-sig-storage-csi-snapshotter:v7.0.2
    - name: rancher/mirrored-sig-storage-livenessprobe:v2.14.0
    - name: rancher/mirrored-sig-storage-snapshot-controller:v8.2.0
    - name: rancher/mirrored-sonobuoy-sonobuoy:v0.57.3
    - name: rancher/nginx-ingress-controller:v1.12.1-hardened6
    - name: rancher/pushprox-client:v0.1.5-rancher2-client
    - name: rancher/pushprox-proxy:v0.1.5-rancher2-proxy
    - name: rancher/rancher-agent:v2.11.3
    - name: rancher/rancher-csp-adapter:v6.0.0
    - name: rancher/rancher:v2.11.3
    - name: rancher/rancher-webhook:v0.7.3
    - name: rancher/remotedialer-proxy:v0.4.4
    - name: rancher/rke2-cloud-provider:v1.32.0-rc3.0.20241220224140-68fbd1a6b543-build20250101
    - name: rancher/rke2-runtime:v1.32.5-rke2r1
    - name: rancher/rke2-upgrade:v1.32.5-rke2r1
    - name: rancher/rke-tools:v0.1.113
    - name: rancher/security-scan:v0.6.0
    - name: rancher/shell:v0.4.1
    - name: rancher/system-agent-installer-k3s:v1.32.5-k3s1
    - name: rancher/system-agent-installer-rke2:v1.32.5-rke2r1
    - name: rancher/system-agent:v0.3.12-suc
    - name: rancher/system-upgrade-controller:v0.15.2
    - name: rancher/ui-plugin-catalog:4.0.1
