apiVersion: content.hauler.cattle.io/v1
kind: Files
metadata:
  name: rancher-airgap-files-rancher-minimal
spec:
  files:
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-ufouo.yaml
      name: rancher-banner-ufouo.yaml
    - path: https://raw.githubusercontent.com/zackbradys/code-templates/main/k8s/yamls/rancher-banner-tssci.yaml
      name: rancher-banner-tssci.yaml
---
apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: rancher-airgap-charts-rancher-minimal
spec:
  charts:
    - name: cert-manager
      repoURL: https://charts.jetstack.io
      version: v1.18.2
    - name: rancher
      repoURL: https://releases.rancher.com/server-charts/latest
      version: 2.12.1
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-cert-manager-images-rancher-minimal
spec:
  images:
    - name: quay.io/jetstack/cert-manager-cainjector:v1.18.2
    - name: quay.io/jetstack/cert-manager-controller:v1.18.2
    - name: quay.io/jetstack/cert-manager-webhook:v1.18.2
    - name: quay.io/jetstack/cert-manager-startupapicheck:v1.18.2
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-rancher-images-rancher-minimal
spec:
  images:
    - name: rancher/backup-restore-operator:v8.0.0
    - name: rancher/compliance-operator:v1.1.0
    - name: rancher/fleet-agent:v0.13.1
    - name: rancher/fleet:v0.13.1
    - name: rancher/hardened-addon-resizer:1.8.23-build20250612
    - name: rancher/hardened-calico:v3.30.2-build20250711
    - name: rancher/hardened-cluster-autoscaler:v1.10.2-build20250611
    - name: rancher/hardened-cni-plugins:v1.7.1-build20250611
    - name: rancher/hardened-coredns:v1.12.2-build20250611
    - name: rancher/hardened-dns-node-cache:1.26.0-build20250611
    - name: rancher/hardened-etcd:v3.5.21-k3s1-build20250612
    - name: rancher/hardened-flannel:v0.27.1-build20250710
    - name: rancher/hardened-k8s-metrics-server:v0.8.0-build20250704
    - name: rancher/hardened-kubernetes:v1.33.3-rke2r1-build20250716
    - name: rancher/hardened-whereabouts:v0.9.1-build20250704
    - name: rancher/k3s-upgrade:v1.33.3-k3s1
    - name: rancher/klipper-helm:v0.9.8-build20250709
    - name: rancher/klipper-lb:v0.4.13
    - name: rancher/kubectl:v1.33.1
    - name: rancher/kuberlr-kubectl:v5.0.0
    - name: rancher/local-path-provisioner:v0.0.31
    - name: rancher/machine:v0.15.0-rancher131
    - name: rancher/mirrored-bci-busybox:15.6.24.2
    - name: rancher/mirrored-bci-micro:15.6.24.2
    - name: rancher/mirrored-brancz-kube-rbac-proxy:v0.18.2
    - name: rancher/mirrored-calico-apiserver:v3.30.1
    - name: rancher/mirrored-calico-cni:v3.30.1
    - name: rancher/mirrored-calico-csi:v3.30.1
    - name: rancher/mirrored-calico-ctl:v3.30.1
    - name: rancher/mirrored-calico-kube-controllers:v3.30.1
    - name: rancher/mirrored-calico-node-driver-registrar:v3.30.1
    - name: rancher/mirrored-calico-node:v3.30.1
    - name: rancher/mirrored-calico-operator:v1.38.1
    - name: rancher/mirrored-calico-pod2daemon-flexvol:v3.30.1
    - name: rancher/mirrored-calico-typha:v3.30.1
    - name: rancher/mirrored-cilium-certgen:v0.2.1
    - name: rancher/mirrored-cilium-cilium-envoy:v1.33.4-1752151664-7c2edb0b44cf95f326d628b837fcdd845102ba68
    - name: rancher/mirrored-cilium-cilium:v1.17.6
    - name: rancher/mirrored-cilium-clustermesh-apiserver:v1.17.6
    - name: rancher/mirrored-cilium-hubble-relay:v1.17.6
    - name: rancher/mirrored-cilium-hubble-ui-backend:v0.13.2
    - name: rancher/mirrored-cilium-hubble-ui:v0.13.2
    - name: rancher/mirrored-cilium-operator-aws:v1.17.6
    - name: rancher/mirrored-cilium-operator-azure:v1.17.6
    - name: rancher/mirrored-cilium-operator-generic:v1.17.6
    - name: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.30.1
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.3.1
    - name: rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.3.1
    - name: rancher/mirrored-cloud-provider-vsphere:v1.33.0
    - name: rancher/mirrored-cluster-api-controller:v1.10.2
    - name: rancher/mirrored-coredns-coredns:1.12.1
    - name: rancher/mirrored-curlimages-curl:8.9.1
    - name: rancher/mirrored-elemental-operator:1.7.3
    - name: rancher/mirrored-elemental-seedimage-builder:1.7.3
    - name: rancher/mirrored-fluent-fluent-bit:3.1.8-debug
    - name: rancher/mirrored-ingress-nginx-kube-webhook-certgen:v1.6.0
    - name: rancher/mirrored-jaegertracing-all-in-one:1.67.0
    - name: rancher/mirrored-jimmidyson-configmap-reload:v0.13.1
    - name: rancher/mirrored-kiali-kiali:v2.7.1
    - name: rancher/mirrored-kiwigrid-k8s-sidecar:1.30.0
    - name: rancher/mirrored-kube-logging-config-reloader:v0.0.6
    - name: rancher/mirrored-kube-logging-fluentd:v1.16-4.10-full
    - name: rancher/mirrored-kube-logging-logging-operator:4.10.0
    - name: rancher/mirrored-kube-state-metrics-kube-state-metrics:v2.15.0
    - name: rancher/mirrored-kube-vip-kube-vip-iptables:v0.8.7
    - name: rancher/mirrored-library-busybox:1.37.0
    - name: rancher/mirrored-library-nginx:1.27.2-alpine
    - name: rancher/mirrored-library-traefik:3.3.6
    - name: rancher/mirrored-messagebird-sachet:0.3.1
    - name: rancher/mirrored-metrics-server:v0.7.2
    - name: rancher/mirrored-pause:3.6
    - name: rancher/mirrored-sig-storage-csi-attacher:v4.7.0
    - name: rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.12.0
    - name: rancher/mirrored-sig-storage-csi-provisioner:v4.0.1
    - name: rancher/mirrored-sig-storage-csi-resizer:v1.10.1
    - name: rancher/mirrored-sig-storage-csi-snapshotter:v7.0.2
    - name: rancher/mirrored-sig-storage-livenessprobe:v2.14.0
    - name: rancher/mirrored-sig-storage-snapshot-controller:v8.2.0
    - name: rancher/mirrored-sonobuoy-sonobuoy:v0.57.3
    - name: rancher/nginx-ingress-controller:v1.12.4-hardened2
    - name: rancher/pushprox-client:v0.1.5-rancher2-client
    - name: rancher/pushprox-proxy:v0.1.5-rancher2-proxy
    - name: rancher/rancher-agent:v2.12.1
    - name: rancher/rancher-csp-adapter:v7.0.0
    - name: rancher/rancher:v2.12.1
    - name: rancher/rancher-webhook:v0.8.1
    - name: rancher/remotedialer-proxy:v0.5.0
    - name: rancher/rke2-cloud-provider:v1.33.1-0.20250516163953-99d91538b132-build20250612
    - name: rancher/rke2-runtime:v1.33.3-rke2r1
    - name: rancher/rke2-upgrade:v1.33.3-rke2r1
    - name: rancher/scc-operator:v0.1.1
    - name: rancher/security-scan:v0.7.1
    - name: rancher/shell:v0.5.0
    - name: rancher/system-agent-installer-k3s:v1.33.3-k3s1
    - name: rancher/system-agent-installer-rke2:v1.33.3-rke2r1
    - name: rancher/system-agent:v0.3.13-suc
    - name: rancher/system-upgrade-controller:v0.16.0
    - name: rancher/ui-plugin-catalog:4.0.3
