name: hauler-workflow
on:
   push:
     tags:
       - '*'

jobs:
  hauler-job-rocky-el9:
    name: Hauler Workflow Job for Rocky Linux 9.1
    runs-on: [self-hosted, linux, X64, rocky, el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la
          yum install -y git libicu

      - name: Build Rancher Airgap Base
        run: |
          sh scripts/base/hauler-base.sh
          mv /opt/rancher/hauler/base/rancher-airgap-base-rocky-el9.yaml hauler/base/rancher-airgap-base-rocky-el9.yaml
          mv /opt/rancher/hauler/base/rancher-airgap-base-rocky-el9.tar.gz hauler/base/rancher-airgap-base-rocky-el9.tar.gz
          ls -la hauler/base
          ls -la scripts/base

      - name: Upload Rancher Airgap Base to Repository
        uses: actions/upload-artifact@v2
        with:
          name: rancher-airgap-base-rocky-el9
          path: hauler/base/rancher-airgap-base-rocky-el9.tar.gz

      - name: Commit and Push Repository
        run: |
          ls -la
          git status
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add *.yaml
          git commit -a -m "updated rancher-airgap for rocky linux 9.1"
          git push

  hauler-job-rhel-el9:
    name: Hauler Workflow Job for RHEL 9.1
    runs-on: [self-hosted, linux, X64, rhel, el9]
    needs: [hauler-job-rocky-el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la
          yum install -y git libicu

      - name: Build Rancher Airgap Base
        run: |
          sh scripts/base/hauler-base.sh
          mv /opt/rancher/hauler/base/rancher-airgap-base-rhel-el9.yaml hauler/base/rancher-airgap-base-rhel-el9.yaml
          mv /opt/rancher/hauler/base/rancher-airgap-base-rhel-el9.tar.gz hauler/base/rancher-airgap-base-rhel-el9.tar.gz
          ls -la hauler/base
          ls -la scripts/base

      - name: Upload Rancher Airgap Base to Repository
        uses: actions/upload-artifact@v2
        with:
          name: rancher-airgap-base-rhel-el9
          path: hauler/base/rancher-airgap-base-rhel-el9.tar.gz

      - name: Commit Changes to Repository
        run: |
          ls -la
          git status
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add *.yaml
          git commit -a -m "updated rancher-airgap for rhel 9.1"
          git push

  rancher-airgap-release:
    name: Rancher Airgap Release Workflow Job
    runs-on: [self-hosted, linux, X64, general]
    needs: [hauler-job-rocky-el9, hauler-job-rhel-el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la
          yum install -y git libicu

      - name: Download Rancher Airgap Base Assets
        uses: actions/download-artifact@v2
        with:
          name: rancher-airgap-base-rocky-el9 rancher-airgap-base-rhel-el9
          path: hauler/base/

      - name: Create Release for Rancher Airgap
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Rancher Airgap Base Rocky Linux 9.1 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hauler/base/rancher-airgap-base-rocky-el9.tar.gz
          asset_name: rancher-airgap-base-rocky-el9.tar.gz
          asset_content_type: application/gzip

      - name: Upload Rancher Airgap Base RHEL 9.1 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hauler/base/rancher-airgap-base-rhel-el9.tar.gz
          asset_name: rancher-airgap-base-rhel-el9.tar.gz
          asset_content_type: application/gzip