name: hauler-workflow
on:
   push:
     tags:
       - '*'

jobs:
  hauler-job-rocky-el9:
    name: Hauler Workflow Job for Rocky Linux 9.1
    runs-on: [self-hosted, linux, X64, rocky, el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la

      - name: Build Rancher Airgap Base
        run: |
          sh hauler/scripts/base/hauler-base.sh
          mv /opt/rancher/hauler/base/rancher-airgap-base-rocky-el9.yaml hauler/base/rancher-airgap-base-rocky-el9.yaml
          mv /opt/rancher/hauler/base/rancher-airgap-base-rocky-el9.tar.zst hauler/base/rancher-airgap-base-rocky-el9.tar.zst
          pwd && ls -la hauler/base
          pwd && ls -la hauler/scripts/base

      - name: Build Rancher Airgap RKE2
        run: |
          sh hauler/scripts/rke2/hauler-rke2.sh
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rocky-el9.yaml hauler/rke2/rancher-airgap-rke2-rocky-el9.yaml
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rocky-el9.tar.zst hauler/rke2/rancher-airgap-rke2-rocky-el9.tar.zst
          pwd && ls -la hauler/rke2
          pwd && ls -la hauler/scripts/rke2

      - name: Setup AWS Credentials/CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-default-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Rancher Airgap to S3 Bucket
        run: |
          aws s3 ls s3://rancher-airgap/
          aws s3 cp hauler s3://rancher-airgap/${{ github.ref }} --recursive
          aws s3 ls s3://rancher-airgap/${{ github.ref }}

      - name: Commit and Push Repository
        continue-on-error: true
        run: |
          pwd && ls -la
          git status
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add *.yaml
          git commit -a -m "updated rancher-airgap for rocky linux 9.1"
          git push

  hauler-job-rhel-el9:
    name: Hauler Workflow Job for RHEL 9.1
    runs-on: [self-hosted, linux, X64, rhel, el9]
    needs: [hauler-job-rocky-el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la

      - name: Build Rancher Airgap Base
        run: |
          sh hauler/scripts/base/hauler-base.sh
          mv /opt/rancher/hauler/base/rancher-airgap-base-rhel-el9.yaml hauler/base/rancher-airgap-base-rhel-el9.yaml
          mv /opt/rancher/hauler/base/rancher-airgap-base-rhel-el9.tar.zst hauler/base/rancher-airgap-base-rhel-el9.tar.zst
          pwd && ls -la hauler/base
          pwd && ls -la hauler/scripts/base

      - name: Build Rancher Airgap RKE2
        run: |
          sh hauler/scripts/rke2/hauler-rke2.sh
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rhel-el9.yaml hauler/rke2/rancher-airgap-rke2-rhel-el9.yaml
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rhel-el9.tar.zst hauler/rke2/rancher-airgap-rke2-rhel-el9.tar.zst
          pwd && ls -la hauler/rke2
          pwd && ls -la hauler/scripts/rke2

      - name: Setup AWS Credentials/CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-default-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Rancher Airgap to S3 Bucket
        run: |
          aws s3 ls s3://rancher-airgap/
          aws s3 cp hauler s3://rancher-airgap/${{ github.ref }} --recursive
          aws s3 ls s3://rancher-airgap/${{ github.ref }}

      - name: Commit and Push Repository
        continue-on-error: true
        run: |
          pwd && ls -la
          git status
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add *.yaml
          git commit -a -m "updated rancher-airgap for rhel 9.1"
          git push

  rancher-airgap-release:
    name: Rancher Airgap Release Workflow Job
    runs-on: [self-hosted, linux, X64, general]
    needs: [hauler-job-rocky-el9, hauler-job-rhel-el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la

      - name: Create Release Notes
        run: |
          echo -e "# Rancher Airgap ${{ github.ref }}\nLatest Release Notes and Asset URLs for the Rancher Airgap Tool. Please review all notes below and ensure to download the correct assets.\n\nRelease for Rocky Linux 9.1:\n*Rancher Airgap Base YAML -> https://rancher-airgap.s3.amazonaws.com/${{ github.ref }}/hauler/base/rancher-airgap-base-rocky-el9.yaml\n*Rancher Airgap Base TAR -> https://rancher-airgap.s3.amazonaws.com/${{ github.ref }}/hauler/base/rancher-airgap-base-rocky-el9.tar.zst\n*Rancher Airgap RKE2 YAML -> https://rancher-airgap.s3.amazonaws.com/${{ github.ref }}/hauler/rke2/rancher-airgap-rke2-rocky-el9.yaml\n*Rancher Airgap RKE2 TAR -> https://rancher-airgap.s3.amazonaws.com/${{ github.ref }}/hauler/rke2/rancher-airgap-rke2-rocky-el9.tar.zst\n\nRelease for RHEL 9.1:\n*Rancher Airgap Base YAML -> https://rancher-airgap.s3.amazonaws.com/${{ github.ref }}/hauler/base/rancher-airgap-base-rhel-el9.yaml\n*Rancher Airgap Base TAR -> https://rancher-airgap.s3.amazonaws.com/${{ github.ref }}/hauler/base/rancher-airgap-base-rhel-el9.tar.zst\n*Rancher Airgap RKE2 YAML -> https://rancher-airgap.s3.amazonaws.com/${{ github.ref }}/hauler/rke2/rancher-airgap-rke2-rhel-el9.yaml\n*Rancher Airgap RKE2 TAR -> https://rancher-airgap.s3.amazonaws.com/${{ github.ref }}/hauler/rke2/rancher-airgap-rke2-rhel-el9.tar.zst\n" > RELEASE-NOTES.MD
          cat RELEASE-NOTES.MD

      - name: Create Release for Rancher Airgap
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Rancher Airgap ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: RELEASE-NOTES.MD