name: hauler-workflow
on:
  push:
    tags:
      - '*'

jobs:
  hauler-job:
    name: Hauler Workflow Job
    runs-on: self-hosted
    steps:
      - name: Hello World
        run: echo 'Hello World!'