name: hauler-workflow
on:
   push:
     tags:
       - '*'

jobs:
  hauler-job-rocky-el9:
    name: Hauler Workflow Job for Rocky Linux 9.1
    runs-on: [self-hosted, linux, X64, rocky, el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: View Repository Structure
        run: pwd && ls -la

      - name: Build Rancher Airgap Base
        run: |
          sh scripts/base/hauler-base.sh
          mv /opt/rancher/hauler/base/rancher-airgap-rocky-el9.tar.zst /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base/rancher-airgap-rocky-el9.tar.zst
          mv /opt/rancher/hauler/base/rancher-airgap-rocky-el9.yaml /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base/rancher-airgap-rocky-el9.yaml
          ls -la /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base
          ls -la /opt/actions-runner/_work/rancher-airgap/rancher-airgap/scripts/base

      - name: Commit and Push Repository
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -a -m "updated rancher-airgap for rocky linux 9.1"
          git push

  hauler-job-rhel-el9:
    name: Hauler Workflow Job for RHEL 9.1
    runs-on: [self-hosted, linux, X64, rhel, el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: View Repository Structure
        run: pwd && ls -la

      - name: Build Rancher Airgap Base
        run: |
          sh scripts/base/hauler-base.sh
          mv /opt/rancher/hauler/base/rancher-airgap-rhel-el9.tar.zst /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base/rancher-airgap-rhel-el9.tar.zst
          mv /opt/rancher/hauler/base/rancher-airgap-rhel-el9.yaml /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base/rancher-airgap-rhel-el9.yaml
          ls -la /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base
          ls -la /opt/actions-runner/_work/rancher-airgap/rancher-airgap/scripts/base

      - name: Commit and Push Repository
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -a -m "updated rancher-airgap for rhel 9.1"
          git push

  rancher-airgap-release:
    name: Rancher Airgap Release Workflow Job
    runs-on: [self-hosted, linux, X64, general]
    needs: [hauler-job-rocky-el9, hauler-job-rhel-el9]
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Rancher Airgap Base Rocky Linux 9.1 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hauler/base/rancher-airgap-base-rocky-el9.tar.gz
          asset_name: rancher-airgap-base-rocky-el9.tar.gz
          asset_content_type: application/gzip

      - name: Upload Rancher Airgap Base RHEL 9.1 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hauler/base/rancher-airgap-base-rhel-el9.tar.gz
          asset_name: rancher-airgap-base-rhel-el9.tar.gz
          asset_content_type: application/gzip