name: hauler-workflow
on: push

jobs:
  hauler-job:
    name: Hauler Workflow Job
    needs: start-runner
    runs-on: self-hosted
    steps:
      - name: Hello World
        run: echo 'Hello World!'