name: hauler-workflow
on:
   push:
     tags:
       - '*'

jobs:
  rancher-airgap-hauler:
    name: Rancher Airgap Job for Hauler
    runs-on: [self-hosted, linux, X64, general]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la

      - name: Build Rancher Airgap Hauler
        run: |
          sh hauler/scripts/hauler/hauler-hauler.sh
          mv /opt/rancher/hauler/hauler/hauler hauler/hauler/hauler
          mv /opt/rancher/hauler/rancher-airgap-hauler.tar.zst hauler/hauler/rancher-airgap-hauler.tar.zst
          pwd && ls -la hauler/hauler
          pwd && ls -la hauler/scripts/hauler

      - name: Build Rancher Airgap RKE2
        run: |
          sh hauler/scripts/rke2/hauler-rke2.sh
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2.yaml hauler/rke2/rancher-airgap-rke2.yaml
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2.tar.zst hauler/rke2/rancher-airgap-rke2.tar.zst
          pwd && ls -la hauler/rke2
          pwd && ls -la hauler/scripts/rke2

      - name: Build Rancher Airgap Rancher
        run: |
          sh hauler/scripts/rancher/hauler-rancher.sh
          mv /opt/rancher/hauler/rancher/rancher-airgap-rancher.yaml hauler/rancher/rancher-airgap-rancher.yaml
          mv /opt/rancher/hauler/rancher/rancher-airgap-rancher.tar.zst hauler/rancher/rancher-airgap-rancher.tar.zst
          pwd && ls -la hauler/rancher
          pwd && ls -la hauler/scripts/rancher

      - name: Build Rancher Airgap Longhorn
        run: |
          sh hauler/scripts/longhorn/hauler-longhorn.sh
          mv /opt/rancher/hauler/longhorn/rancher-airgap-longhorn.yaml hauler/longhorn/rancher-airgap-longhorn.yaml
          mv /opt/rancher/hauler/longhorn/rancher-airgap-longhorn.tar.zst hauler/longhorn/rancher-airgap-longhorn.tar.zst
          pwd && ls -la hauler/longhorn
          pwd && ls -la hauler/scripts/longhorn

      - name: Build Rancher Airgap NeuVector
        run: |
          sh hauler/scripts/neuvector/hauler-neuvector.sh
          mv /opt/rancher/hauler/neuvector/rancher-airgap-neuvector.yaml hauler/neuvector/rancher-airgap-neuvector.yaml
          mv /opt/rancher/hauler/neuvector/rancher-airgap-neuvector.tar.zst hauler/neuvector/rancher-airgap-neuvector.tar.zst
          pwd && ls -la hauler/neuvector
          pwd && ls -la hauler/scripts/neuvector

      - name: Setup AWS Credentials/CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Assets to AWS S3 Bucket
        run: |
          aws s3 ls s3://rancher-airgap/
          aws s3 cp hauler s3://rancher-airgap/${GITHUB_REF##*/}/hauler --recursive
          aws s3 ls s3://rancher-airgap/${GITHUB_REF##*/}/hauler

      - name: Commit and Push Repository
        continue-on-error: true
        run: |
          pwd && ls -la
          git status
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add hauler *.yaml
          git commit -a -m "updated rancher airgap assets [github-actions]"
          git push

  rancher-airgap-release:
    name: Rancher Airgap Release Workflow Job
    runs-on: [self-hosted, linux, X64, general]
    needs: [rancher-airgap-hauler]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la

      - name: Create Release Notes
        run: |
          echo -e "# Rancher Airgap Release ${GITHUB_REF##*/}\nLatest Release Notes and Asset URLs. Please review all notes below and ensure to download the correct assets. Please utilize GitHub Issues, Forks, and/or Pull Requests to submit any issues, updates, or fixes! Thank you.\n\nThese Release Notes were generated automatically by **[github-actions]**.\n\n## Upgrade Steps\n* No upgrade steps for this release.\n\n## Breaking Changes\n* No breaking changes for this release.\n\n## Features and Improvements\n* No features or improvements for this release.\n\n## Bug Fixes and Additional Notes\n* No bug fixes or additional notes for this release.\n\n## Release Assets for the Rancher Airgap\n\n### Hauler (by Rancher Government Solutions)\n* **TAR ->** [s3://rancher-airgap-hauler.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/hauler/rancher-airgap-hauler.tar.zst)\n\n### Rancher Kubernetes Engine 2 (RKE2)\n* **Hauler YAML ->** [s3://rancher-airgap-rke2.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rke2/rancher-airgap-rke2.yaml)\n* **TAR ->** [s3://rancher-airgap-rke2.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rke2/rancher-airgap-rke2.tar.zst)\n\n### Rancher Multi-Cluster-Manager (MCM)\n* **Hauler YAML ->** [s3://rancher-airgap-rancher.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rancher/rancher-airgap-rancher.yaml)\n* **TAR ->** [s3://rancher-airgap-rancher.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rancher/rancher-airgap-rancher.tar.zst)\n\n### Rancher Longhorn (LH)\n* **Hauler YAML ->** [s3://rancher-airgap-longhorn.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/longhorn/rancher-airgap-longhorn.yaml)\n* **TAR ->** [s3://rancher-airgap-longhorn.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/longhorn/rancher-airgap-longhorn.tar.zst)\n\n### Rancher NeuVector (NV)\n* **Hauler YAML ->** [s3://rancher-airgap-neuvector.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/neuvector/rancher-airgap-neuvector.yaml)\n* **TAR ->** [s3://rancher-airgap-neuvector.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/neuvector/rancher-airgap-neuvector.tar.zst)" > RELEASE-NOTES.MD
          echo Previewing Release Notes:
          cat RELEASE-NOTES.MD

      - name: Create Release with Release Notes
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Rancher Airgap ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: RELEASE-NOTES.MD