name: hauler-workflow
on:
   push:
     tags:
       - '*'

jobs:
  hauler-job-rocky-el9:
    name: Hauler Workflow Job for Rocky Linux 9.1
    runs-on: [self-hosted, linux, X64, rocky, el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la

      - name: Build Rancher Airgap Base
        run: |
          sh hauler/scripts/base/hauler-base.sh
          mv /opt/rancher/hauler/base/rancher-airgap-base-rocky-el9.yaml hauler/base/rancher-airgap-base-rocky-el9.yaml
          mv /opt/rancher/hauler/base/rancher-airgap-base-rocky-el9.tar.zst hauler/base/rancher-airgap-base-rocky-el9.tar.zst
          pwd && ls -la hauler/base
          pwd && ls -la hauler/scripts/base

      - name: Build Rancher Airgap RKE2
        run: |
          sh hauler/scripts/rke2/hauler-rke2.sh
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rocky-el9.yaml hauler/rke2/rancher-airgap-rke2-rocky-el9.yaml
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rocky-el9.tar.zst hauler/rke2/rancher-airgap-rke2-rocky-el9.tar.zst
          pwd && ls -la hauler/rke2
          pwd && ls -la hauler/scripts/rke2

      - name: Build Rancher Airgap Rancher
        run: |
          sh hauler/scripts/rancher/hauler-rancher.sh
          mv /opt/rancher/hauler/rancher/rancher-airgap-rancher-rocky-el9.yaml hauler/rancher/rancher-airgap-rancher-rocky-el9.yaml
          mv /opt/rancher/hauler/rancher/rancher-airgap-rancher-rocky-el9.tar.zst hauler/rancher/rancher-airgap-rancher-rocky-el9.tar.zst
          pwd && ls -la hauler/rancher
          pwd && ls -la hauler/scripts/rancher

      - name: Build Rancher Airgap Longhorn
        run: |
          sh hauler/scripts/longhorn/hauler-longhorn.sh
          mv /opt/rancher/hauler/longhorn/rancher-airgap-longhorn-rocky-el9.yaml hauler/longhorn/rancher-airgap-longhorn-rocky-el9.yaml
          mv /opt/rancher/hauler/longhorn/rancher-airgap-longhorn-rocky-el9.tar.zst hauler/longhorn/rancher-airgap-longhorn-rocky-el9.tar.zst
          pwd && ls -la hauler/longhorn
          pwd && ls -la hauler/scripts/longhorn

      - name: Build Rancher Airgap NeuVector
        run: |
          sh hauler/scripts/neuvector/hauler-neuvector.sh
          mv /opt/rancher/hauler/neuvector/rancher-airgap-neuvector-rocky-el9.yaml hauler/neuvector/rancher-airgap-neuvector-rocky-el9.yaml
          mv /opt/rancher/hauler/neuvector/rancher-airgap-neuvector-rocky-el9.tar.zst hauler/neuvector/rancher-airgap-neuvector-rocky-el9.tar.zst
          pwd && ls -la hauler/neuvector
          pwd && ls -la hauler/scripts/neuvector

      - name: Setup AWS Credentials/CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Assets to AWS S3 Bucket
        run: |
          aws s3 ls s3://rancher-airgap/
          aws s3 cp hauler s3://rancher-airgap/${GITHUB_REF##*/}/hauler --recursive
          aws s3 ls s3://rancher-airgap/${GITHUB_REF##*/}/hauler

      - name: Commit and Push Repository
        continue-on-error: true
        run: |
          pwd && ls -la
          git status
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add *.yaml
          git commit -a -m "updated rancher airgap for rocky linux 9.1"
          git push

  hauler-job-rhel-el9:
    name: Hauler Workflow Job for RHEL 9.1
    runs-on: [self-hosted, linux, X64, rhel, el9]
    needs: [hauler-job-rocky-el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la

      - name: Build Rancher Airgap Base
        run: |
          sh hauler/scripts/base/hauler-base.sh
          mv /opt/rancher/hauler/base/rancher-airgap-base-rhel-el9.yaml hauler/base/rancher-airgap-base-rhel-el9.yaml
          mv /opt/rancher/hauler/base/rancher-airgap-base-rhel-el9.tar.zst hauler/base/rancher-airgap-base-rhel-el9.tar.zst
          pwd && ls -la hauler/base
          pwd && ls -la hauler/scripts/base

      - name: Build Rancher Airgap RKE2
        run: |
          sh hauler/scripts/rke2/hauler-rke2.sh
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rhel-el9.yaml hauler/rke2/rancher-airgap-rke2-rhel-el9.yaml
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rhel-el9.tar.zst hauler/rke2/rancher-airgap-rke2-rhel-el9.tar.zst
          pwd && ls -la hauler/rke2
          pwd && ls -la hauler/scripts/rke2

      - name: Build Rancher Airgap Rancher
        run: |
          sh hauler/scripts/rancher/hauler-rancher.sh
          mv /opt/rancher/hauler/rancher/rancher-airgap-rancher-rhel-el9.yaml hauler/rancher/rancher-airgap-rancher-rhel-el9.yaml
          mv /opt/rancher/hauler/rancher/rancher-airgap-rancher-rhel-el9.tar.zst hauler/rancher/rancher-airgap-rancher-rhel-el9.tar.zst
          pwd && ls -la hauler/rancher
          pwd && ls -la hauler/scripts/rancher

      - name: Build Rancher Airgap Longhorn
        run: |
          sh hauler/scripts/longhorn/hauler-longhorn.sh
          mv /opt/rancher/hauler/longhorn/rancher-airgap-longhorn-rhel-el9.yaml hauler/longhorn/rancher-airgap-longhorn-rhel-el9.yaml
          mv /opt/rancher/hauler/longhorn/rancher-airgap-longhorn-rhel-el9.tar.zst hauler/longhorn/rancher-airgap-longhorn-rhel-el9.tar.zst
          pwd && ls -la hauler/longhorn
          pwd && ls -la hauler/scripts/longhorn

      - name: Build Rancher Airgap NeuVector
        run: |
          sh hauler/scripts/neuvector/hauler-neuvector.sh
          mv /opt/rancher/hauler/neuvector/rancher-airgap-neuvector-rhel-el9.yaml hauler/neuvector/rancher-airgap-neuvector-rhel-el9.yaml
          mv /opt/rancher/hauler/neuvector/rancher-airgap-neuvector-rhel-el9.tar.zst hauler/neuvector/rancher-airgap-neuvector-rhel-el9.tar.zst
          pwd && ls -la hauler/neuvector
          pwd && ls -la hauler/scripts/neuvector

      - name: Setup AWS Credentials/CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Assets to AWS S3 Bucket
        run: |
          aws s3 ls s3://rancher-airgap/
          aws s3 cp hauler s3://rancher-airgap/${GITHUB_REF##*/}/hauler --recursive
          aws s3 ls s3://rancher-airgap/${GITHUB_REF##*/}/hauler

      - name: Commit and Push Repository
        continue-on-error: true
        run: |
          pwd && ls -la
          git status
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add *.yaml
          git commit -a -m "updated rancher airgap for rhel 9.1"
          git push

  hauler-job-rocky-el8:
    name: Hauler Workflow Job for Rocky Linux 8.5
    runs-on: [self-hosted, linux, X64, rocky, el8]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la

      - name: Build Rancher Airgap Base
        run: |
          sh hauler/scripts/base/hauler-base.sh
          mv /opt/rancher/hauler/base/rancher-airgap-base-rocky-el8.yaml hauler/base/rancher-airgap-base-rocky-el8.yaml
          mv /opt/rancher/hauler/base/rancher-airgap-base-rocky-el8.tar.zst hauler/base/rancher-airgap-base-rocky-el8.tar.zst
          pwd && ls -la hauler/base
          pwd && ls -la hauler/scripts/base

      - name: Build Rancher Airgap RKE2
        run: |
          sh hauler/scripts/rke2/hauler-rke2.sh
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rocky-el8.yaml hauler/rke2/rancher-airgap-rke2-rocky-el8.yaml
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rocky-el8.tar.zst hauler/rke2/rancher-airgap-rke2-rocky-el8.tar.zst
          pwd && ls -la hauler/rke2
          pwd && ls -la hauler/scripts/rke2

      - name: Build Rancher Airgap Rancher
        run: |
          sh hauler/scripts/rancher/hauler-rancher.sh
          mv /opt/rancher/hauler/rancher/rancher-airgap-rancher-rocky-el8.yaml hauler/rancher/rancher-airgap-rancher-rocky-el8.yaml
          mv /opt/rancher/hauler/rancher/rancher-airgap-rancher-rocky-el8.tar.zst hauler/rancher/rancher-airgap-rancher-rocky-el8.tar.zst
          pwd && ls -la hauler/rancher
          pwd && ls -la hauler/scripts/rancher

      - name: Build Rancher Airgap Longhorn
        run: |
          sh hauler/scripts/longhorn/hauler-longhorn.sh
          mv /opt/rancher/hauler/longhorn/rancher-airgap-longhorn-rocky-el8.yaml hauler/longhorn/rancher-airgap-longhorn-rocky-el8.yaml
          mv /opt/rancher/hauler/longhorn/rancher-airgap-longhorn-rocky-el8.tar.zst hauler/longhorn/rancher-airgap-longhorn-rocky-el8.tar.zst
          pwd && ls -la hauler/longhorn
          pwd && ls -la hauler/scripts/longhorn

      - name: Build Rancher Airgap NeuVector
        run: |
          sh hauler/scripts/neuvector/hauler-neuvector.sh
          mv /opt/rancher/hauler/neuvector/rancher-airgap-neuvector-rocky-el8.yaml hauler/neuvector/rancher-airgap-neuvector-rocky-el8.yaml
          mv /opt/rancher/hauler/neuvector/rancher-airgap-neuvector-rocky-el8.tar.zst hauler/neuvector/rancher-airgap-neuvector-rocky-el8.tar.zst
          pwd && ls -la hauler/neuvector
          pwd && ls -la hauler/scripts/neuvector

      - name: Setup AWS Credentials/CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Assets to AWS S3 Bucket
        run: |
          aws s3 ls s3://rancher-airgap/
          aws s3 cp hauler s3://rancher-airgap/${GITHUB_REF##*/}/hauler --recursive
          aws s3 ls s3://rancher-airgap/${GITHUB_REF##*/}/hauler

      - name: Commit and Push Repository
        continue-on-error: true
        run: |
          pwd && ls -la
          git status
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add *.yaml
          git commit -a -m "updated rancher airgap for rocky linux 8.5"
          git push

  hauler-job-rhel-el8:
    name: Hauler Workflow Job for RHEL 8.5
    runs-on: [self-hosted, linux, X64, rhel, el8]
    needs: [hauler-job-rocky-el8]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la

      - name: Build Rancher Airgap Base
        run: |
          sh hauler/scripts/base/hauler-base.sh
          mv /opt/rancher/hauler/base/rancher-airgap-base-rhel-el8.yaml hauler/base/rancher-airgap-base-rhel-el8.yaml
          mv /opt/rancher/hauler/base/rancher-airgap-base-rhel-el8.tar.zst hauler/base/rancher-airgap-base-rhel-el8.tar.zst
          pwd && ls -la hauler/base
          pwd && ls -la hauler/scripts/base

      - name: Build Rancher Airgap RKE2
        run: |
          sh hauler/scripts/rke2/hauler-rke2.sh
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rhel-el8.yaml hauler/rke2/rancher-airgap-rke2-rhel-el8.yaml
          mv /opt/rancher/hauler/rke2/rancher-airgap-rke2-rhel-el8.tar.zst hauler/rke2/rancher-airgap-rke2-rhel-el8.tar.zst
          pwd && ls -la hauler/rke2
          pwd && ls -la hauler/scripts/rke2

      - name: Build Rancher Airgap Rancher
        run: |
          sh hauler/scripts/rancher/hauler-rancher.sh
          mv /opt/rancher/hauler/rancher/rancher-airgap-rancher-rhel-el8.yaml hauler/rancher/rancher-airgap-rancher-rhel-el8.yaml
          mv /opt/rancher/hauler/rancher/rancher-airgap-rancher-rhel-el8.tar.zst hauler/rancher/rancher-airgap-rancher-rhel-el8.tar.zst
          pwd && ls -la hauler/rancher
          pwd && ls -la hauler/scripts/rancher

      - name: Build Rancher Airgap Longhorn
        run: |
          sh hauler/scripts/longhorn/hauler-longhorn.sh
          mv /opt/rancher/hauler/longhorn/rancher-airgap-longhorn-rhel-el8.yaml hauler/longhorn/rancher-airgap-longhorn-rhel-el8.yaml
          mv /opt/rancher/hauler/longhorn/rancher-airgap-longhorn-rhel-el8.tar.zst hauler/longhorn/rancher-airgap-longhorn-rhel-el8.tar.zst
          pwd && ls -la hauler/longhorn
          pwd && ls -la hauler/scripts/longhorn

      - name: Build Rancher Airgap NeuVector
        run: |
          sh hauler/scripts/neuvector/hauler-neuvector.sh
          mv /opt/rancher/hauler/neuvector/rancher-airgap-neuvector-rhel-el8.yaml hauler/neuvector/rancher-airgap-neuvector-rhel-el8.yaml
          mv /opt/rancher/hauler/neuvector/rancher-airgap-neuvector-rhel-el8.tar.zst hauler/neuvector/rancher-airgap-neuvector-rhel-el8.tar.zst
          pwd && ls -la hauler/neuvector
          pwd && ls -la hauler/scripts/neuvector

      - name: Setup AWS Credentials/CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Assets to AWS S3 Bucket
        run: |
          aws s3 ls s3://rancher-airgap/
          aws s3 cp hauler s3://rancher-airgap/${GITHUB_REF##*/}/hauler --recursive
          aws s3 ls s3://rancher-airgap/${GITHUB_REF##*/}/hauler

      - name: Commit and Push Repository
        continue-on-error: true
        run: |
          pwd && ls -la
          git status
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add *.yaml
          git commit -a -m "updated rancher airgap for rhel 8.5"
          git push

  rancher-airgap-release:
    name: Rancher Airgap Release Workflow Job
    runs-on: [self-hosted, linux, X64, general]
    needs: [hauler-job-rocky-el9, hauler-job-rhel-el9, hauler-job-rocky-el8, hauler-job-rhel-el8]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Prebuild Setup/Checks
        run: |
          pwd && ls -la

      - name: Create Release Notes
        run: |
          echo -e "# Rancher Airgap Release ${GITHUB_REF##*/}\nLatest Release Notes and Asset URLs. Please review all notes below and ensure to download the correct assets. Please utilize GitHub Issues, Forks, and/or Pull Requests to submit any issues, updates, or fixes! Thank you.\n\n## Upgrade Steps\n\n## Breaking Changes\n\n## Features and Improvements\n\n## Bug Fixes and Notes\n\n\n## Release for Rocky Linux 9.1\n* **Base YAML ->** [s3://rancher-airgap-base-rocky-el9.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/base/rancher-airgap-base-rocky-el9.yaml)\n* **Base TAR ->** [s3://rancher-airgap-base-rocky-el9.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/base/rancher-airgap-base-rocky-el9.tar.zst)\n* **RKE2 YAML ->** [s3://rancher-airgap-rke2-rocky-el9.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rke2/rancher-airgap-rke2-rocky-el9.yaml)\n* **RKE2 TAR ->** [s3://rancher-airgap-rke2-rocky-el9.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rke2/rancher-airgap-rke2-rocky-el9.tar.zst)\n\n\n## Release for RHEL 9.1:\n* **Base YAML ->** [s3://rancher-airgap-base-rhel-el9.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/base/rancher-airgap-base-rhel-el9.yaml)\n* **Base TAR ->** [s3://rancher-airgap-base-rhel-el9.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/base/rancher-airgap-base-rhel-el9.tar.zst)\n* **RKE2 YAML ->** [s3://rancher-airgap-rke2-rhel-el9.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rke2/rancher-airgap-rke2-rhel-el9.yaml)\n* **RKE2 TAR ->** [s3://rancher-airgap-rke2-rhel-el9.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rke2/rancher-airgap-rke2-rhel-el9.tar.zst)\n\n\n## Release for Rocky Linux 8.5\n* **Base YAML ->** [s3://rancher-airgap-base-rocky-el8.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/base/rancher-airgap-base-rocky-el8.yaml)\n* **Base TAR ->** [s3://rancher-airgap-base-rocky-el8.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/base/rancher-airgap-base-rocky-el8.tar.zst)\n* **RKE2 YAML ->** [s3://rancher-airgap-rke2-rocky-el8.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rke2/rancher-airgap-rke2-rocky-el8.yaml)\n* **RKE2 TAR ->** [s3://rancher-airgap-rke2-rocky-el8.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rke2/rancher-airgap-rke2-rocky-el8.tar.zst)\n\n\n## Release for RHEL 8.5:\n* **Base YAML ->** [s3://rancher-airgap-base-rhel-el8.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/base/rancher-airgap-base-rhel-el8.yaml)\n* **Base TAR ->** [s3://rancher-airgap-base-rhel-el8.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/base/rancher-airgap-base-rhel-el8.tar.zst)\n* **RKE2 YAML ->** [s3://rancher-airgap-rke2-rhel-el8.yaml](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rke2/rancher-airgap-rke2-rhel-el8.yaml)\n* **RKE2 TAR ->** [s3://rancher-airgap-rke2-rhel-el8.tar.zst](https://rancher-airgap.s3.amazonaws.com/${GITHUB_REF##*/}/hauler/rke2/rancher-airgap-rke2-rhel-el8.tar.zst)\n" > RELEASE-NOTES.MD
          echo Previewing Release Notes:
          cat RELEASE-NOTES.MD

      - name: Create Release with Release Notes
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Rancher Airgap ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: RELEASE-NOTES.MD