name: hauler-workflow
on: push

jobs:
  hauler-job-rocky-el9:
    name: Hauler Workflow Job for Rocky Linux 9.1
    runs-on: [self-hosted, linux, X64, rocky, el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: View Repository Structure
        run: ls -la

      - name: Build Rancher Airgap Base
        run: |
          sh scripts/base/hauler-base.sh
          pwd
          cd /opt/rancher/hauler/base/
          ls -la
          mv rancher-airgap-rocky-el9.tar.zst /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base/rancher-airgap-rocky-el9.tar.zst
          mv rancher-airgap-rocky-el9.yaml /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base/rancher-airgap-rocky-el9.yaml
          pwd
          ls -la
          ls -la /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base
          ls -la /opt/actions-runner/_work/rancher-airgap/rancher-airgap/scripts/base

  hauler-job-rhel-el9:
    name: Hauler Workflow Job for RHEL 9.1
    runs-on: [self-hosted, linux, X64, rhel, el9]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: View Repository Structure
        run: ls -la

      - name: Build Rancher Airgap Base
        run: |
          sh scripts/base/hauler-base.sh
          pwd
          cd /opt/rancher/hauler/base/
          ls -la
          mv rancher-airgap-rocky-el9.tar.zst /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base/rancher-airgap-rocky-el9.tar.zst
          mv rancher-airgap-rocky-el9.yaml /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base/rancher-airgap-rocky-el9.yaml
          pwd
          ls -la
          ls -la /opt/actions-runner/_work/rancher-airgap/rancher-airgap/hauler/base
          ls -la /opt/actions-runner/_work/rancher-airgap/rancher-airgap/scripts/base