apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: rancher-airgap-charts-neuvector
spec:
  charts:
    - name: core
      repoURL: https://neuvector.github.io/neuvector-helm
      version: 2.7.6
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-images-neuvector
spec:
  images:
    - name: neuvector/enforcer:5.3.2
    - name: neuvector/controller:5.3.2
    - name: neuvector/manager:5.3.2
    - name: neuvector/scanner:latest
    - name: neuvector/updater:latest
