apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: rancher-airgap-charts-neuvector
spec:
  charts:
    - name: core
      repoURL: https://neuvector.github.io/neuvector-helm
      version: 2.8.5
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: rancher-airgap-images-neuvector
spec:
  images:
    - name: neuvector/enforcer:5.4.3
    - name: neuvector/controller:5.4.3
    - name: neuvector/controller:5.4.3
    - name: neuvector/manager:5.4.3
    - name: neuvector/scanner:6
    - name: neuvector/updater:0.0.2
    - name: neuvector/controller:5.4.3
